/* Generated by assets/equipment/generate_data.py; do not hand edit. */
#include "equipment.h"

const EquipmentItemId equipment_authored_ids[EQUIPMENT_AUTHORED_COUNT] = {
    1, 2, 9, 10, 17, 18, 33, 34, 49, 50, 65, 81, 82, 3, 11, 19, 35, 51, 83, 4, 12, 36, 52, 66, 84, 20, 37, 53, 67, 85, 5, 6, 13, 38, 54, 68, 86, 21, 39, 55, 69, 87, 7, 14, 56, 88, 40, 89
};

const EquipmentDefinition equipment_definitions[EQUIPMENT_DEFINITION_CAPACITY] = {
    [1] = {1, 0, 1, 1, 255, {0, 0}, {0, 0, 0, 0, 0, 0, 0, 0}},
    [2] = {2, 0, 1, 0, 255, {0, 0}, {4, 1, 0, 0, 0, 0, 0, 0}},
    [9] = {9, 0, 2, 0, 255, {0, 0}, {0, 0, 0, 0, 0, 0, 0, 0}},
    [10] = {10, 0, 2, 0, 255, {0, 0}, {4, 0, 0, 0, 0, 0, 0, 1}},
    [17] = {17, 0, 3, 0, 255, {0, 0}, {0, 0, 0, 0, 0, 0, 0, 0}},
    [18] = {18, 0, 3, 0, 255, {0, 0}, {4, 0, 0, 0, 0, 0, 0, 0}},
    [33] = {33, 1, 0, 0, 255, {0, 0}, {0, 2, 8, -4, 0, 0, 0, 0}},
    [34] = {34, 1, 0, 0, 255, {0, 0}, {0, 4, 16, -8, 0, 0, 0, 0}},
    [49] = {49, 2, 0, 0, 255, {0, 0}, {0, 0, 0, 8, 0, 0, 0, 0}},
    [50] = {50, 2, 0, 0, 255, {0, 0}, {0, 0, 0, 0, 3, 0, 0, 0}},
    [65] = {65, 3, 0, 0, 255, {0, 0}, {0, 0, 8, 0, 0, 0, 0, 0}},
    [81] = {81, 4, 0, 0, 255, {0, 0}, {0, 0, 0, 0, 0, 4, 0, 0}},
    [82] = {82, 4, 0, 0, 255, {0, 0}, {0, 1, 0, 0, 0, 0, 0, 1}},
    [3] = {3, 0, 1, 0, 255, {0, 0}, {2, 0, 0, 0, 0, 0, 3, 0}},
    [11] = {11, 0, 2, 0, 255, {0, 0}, {2, 1, 0, 0, 0, 0, 0, 0}},
    [19] = {19, 0, 3, 0, 255, {0, 0}, {1, 0, 0, 0, 0, 0, 12, 0}},
    [35] = {35, 1, 0, 0, 255, {0, 0}, {0, 1, 4, 0, 0, 0, 0, 0}},
    [51] = {51, 2, 0, 0, 255, {0, 0}, {0, 0, 0, 4, 1, 0, 0, 0}},
    [83] = {83, 4, 0, 0, 255, {0, 0}, {0, 1, 0, 0, 0, 2, 0, 0}},
    [4] = {4, 0, 1, 0, 255, {0, 0}, {0, 0, 0, 0, 0, 0, 1, 1}},
    [12] = {12, 0, 2, 0, 255, {0, 0}, {0, 0, 0, 0, 0, 0, 4, 0}},
    [36] = {36, 1, 0, 0, 255, {0, 0}, {0, 3, 0, -2, 0, 0, 0, 0}},
    [52] = {52, 2, 0, 0, 255, {0, 0}, {0, 0, 0, -4, 4, 0, 0, 0}},
    [66] = {66, 3, 0, 0, 255, {0, 0}, {0, 0, 4, 0, 0, 1, 0, 0}},
    [84] = {84, 4, 0, 0, 255, {0, 0}, {0, 0, 0, -4, 0, 0, 0, 2}},
    [20] = {20, 0, 3, 0, 255, {0, 0}, {2, 0, 0, 0, 0, 0, 6, 0}},
    [37] = {37, 1, 0, 0, 255, {0, 0}, {0, 2, 8, -2, 0, 0, 0, 0}},
    [53] = {53, 2, 0, 0, 255, {0, 0}, {0, 0, 4, 4, 0, 0, 0, 0}},
    [67] = {67, 3, 0, 0, 255, {0, 0}, {0, 1, 0, -2, 0, 0, 0, 1}},
    [85] = {85, 4, 0, 0, 255, {0, 0}, {0, 0, 0, 2, 0, 3, 0, 0}},
    [5] = {5, 0, 1, 0, 255, {0, 0}, {2, 0, 0, -2, 0, 0, 2, 0}},
    [6] = {6, 0, 1, 0, 255, {0, 0}, {1, 0, 0, 0, 0, 0, 3, 0}},
    [13] = {13, 0, 2, 0, 255, {0, 0}, {0, 1, 0, -2, 0, 0, 4, 0}},
    [38] = {38, 1, 0, 0, 255, {0, 0}, {0, 2, 4, 0, 0, 0, 0, 0}},
    [54] = {54, 2, 0, 0, 255, {0, 0}, {0, 0, 0, 6, 1, 0, 0, 0}},
    [68] = {68, 3, 0, 0, 255, {0, 0}, {0, 0, 8, -2, 0, 2, 0, 0}},
    [86] = {86, 4, 0, 0, 255, {0, 0}, {0, 1, 0, 0, 0, 2, 0, 0}},
    [21] = {21, 0, 3, 0, 255, {0, 0}, {0, 0, 0, 4, 0, 0, 8, 0}},
    [39] = {39, 1, 0, 0, 255, {0, 0}, {0, 3, 4, -2, 0, 0, 0, 0}},
    [55] = {55, 2, 0, 0, 255, {0, 0}, {0, 0, 0, 4, 2, 0, 0, 0}},
    [69] = {69, 3, 0, 0, 255, {0, 0}, {0, 0, 4, 0, 0, 3, 0, 0}},
    [87] = {87, 4, 0, 0, 255, {0, 0}, {0, 1, 0, -2, 0, 1, 0, 1}},
    [7] = {7, 0, 1, 0, 255, {0, 0}, {1, 0, 0, -2, 0, 0, 1, 1}},
    [14] = {14, 0, 2, 0, 255, {0, 0}, {0, 0, 4, -2, 0, 0, 2, 0}},
    [56] = {56, 2, 0, 0, 255, {0, 0}, {0, 0, 8, -2, 1, 0, 0, 0}},
    [88] = {88, 4, 0, 0, 255, {0, 0}, {0, 0, 0, -2, 0, 5, 0, 0}},
    [40] = {40, 1, 0, 0, 255, {0, 0}, {0, 1, 16, -4, 0, 0, 0, 0}},
    [89] = {89, 4, 0, 0, 255, {0, 0}, {0, 0, 0, -4, 1, 4, 0, 0}},
};

const EquipmentWeapon equipment_weapons[4] = {
    [1] = {1, 3, 44, 8, 384, 0, 0, 0, 0, 0, {{2, 1, 14, 32, 29, 18}, {2, 1, 14, 32, 29, 18}, {3, 1, 20, 48, 35, 20}}},
    [2] = {2, 1, 0, 6, 256, 0, 0, 0, 0, 0, {{6, 3, 20, 48, 43, 6}, {0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0}}},
    [3] = {3, 2, 0, 0, 0, 1024, 24, 45, 2, 0, {{4, 1, 23, 32, 112, 3}, {24, 1, 23, 48, 144, 3}, {0, 0, 0, 0, 0, 0}}},
};

const char *equipment_name(unsigned id) {
    switch (id) {
    case 1: return "Wayfarer Sword";
    case 2: return "Reedguard Sword";
    case 9: return "Practice Lance";
    case 10: return "Copperleaf Lance";
    case 17: return "Travel Bow";
    case 18: return "Tidewood Bow";
    case 33: return "Patchwork Mail";
    case 34: return "Hearthscale Mail";
    case 49: return "Trail Boots";
    case 50: return "Surestep Boots";
    case 65: return "Woven Belt";
    case 81: return "Resonance Ring";
    case 82: return "Steady Ring";
    case 3: return "Ropeguard Sword";
    case 11: return "Quay Lance";
    case 19: return "Headland Bow";
    case 35: return "Sailcloth Mail";
    case 51: return "Deck Boots";
    case 83: return "Bearing Ring";
    case 4: return "Shadecutter Sword";
    case 12: return "Sunlace Lance";
    case 36: return "Breezewall Mail";
    case 52: return "Softsand Boots";
    case 66: return "Raincatch Belt";
    case 84: return "Springpin Ring";
    case 20: return "Ventstring Bow";
    case 37: return "Kilnweave Mail";
    case 53: return "Pumice Boots";
    case 67: return "Bricklayer Belt";
    case 85: return "Quietnote Ring";
    case 5: return "Terrace Sword";
    case 6: return "Shellscribe Sword";
    case 13: return "Nacrepoint Lance";
    case 38: return "Pearlweave Mail";
    case 54: return "Driftstep Boots";
    case 68: return "Mapfold Belt";
    case 86: return "Quietwater Ring";
    case 21: return "Sailthread Bow";
    case 39: return "Homeweave Mail";
    case 55: return "Walkway Boots";
    case 69: return "Reedcourier Belt";
    case 87: return "Patient Ring";
    case 7: return "Bridgegrain Sword";
    case 14: return "Rainstair Lance";
    case 56: return "Shelter Boots";
    case 88: return "Listening Ring";
    case 40: return "Wayfarer Coat";
    case 89: return "Porchlight Ring";
    default: return "Empty";
    }
}

const char *equipment_description(unsigned id, unsigned line) {
    if (line > 1) return "";
    switch (id) {
    case 1: return line ? "Cannot be discarded." : "A trusty close-range sword.";
    case 2: return line ? "Attack +4; defense +1." : "A sturdier close-range cut.";
    case 9: return line ? "Long reach; watch your sides." : "A narrow, committed thrust.";
    case 10: return line ? "Attack +4; stagger +1." : "Copperleaf tips hold firm.";
    case 17: return line ? "Arrows carry no field magic." : "Aim and release to fire.";
    case 18: return line ? "Attack +4 on each arrow." : "A steady bow for long roads.";
    case 33: return line ? "Defense +2; speed -4." : "A half-heart of padding.";
    case 34: return line ? "Defense +4; speed -8." : "A heart of layered armor.";
    case 49: return line ? "Walking speed +8." : "Light soles for the trail.";
    case 50: return line ? "Roll cooldown -3." : "Sure footing after a dodge.";
    case 65: return line ? "Maximum health +half-heart." : "A packmaker's sturdy belt.";
    case 81: return line ? "Power cooldown -4." : "A clear note for companions.";
    case 82: return line ? "Defense +1; stagger +1." : "A ring that steadies the hand.";
    case 3: return line ? "Attack +2; reach +3." : "A lighter cut with a longer reach.";
    case 11: return line ? "Attack +2; defense +1." : "A balanced harbor thrust.";
    case 19: return line ? "Attack +1; range +12." : "A lighter arrow that travels farther.";
    case 35: return line ? "Defense +1; health +1/4 heart." : "Light padding leaves your stride free.";
    case 51: return line ? "Speed +4; roll recovery -1." : "Sure steps and a quicker second roll.";
    case 83: return line ? "Defense +1; power recovery -2." : "A measured balance of guard and focus.";
    case 4: return line ? "Reach +1; stagger +1." : "A light cut that interrupts.";
    case 12: return line ? "Reach +4; no attack bonus." : "A long point for careful spacing.";
    case 36: return line ? "Defense +3; speed -2." : "A breezy guard without padding.";
    case 52: return line ? "Roll cooldown -4; speed -4." : "Soft soles steady the next roll.";
    case 66: return line ? "Power cooldown -1." : "A quarter-heart reserve.";
    case 84: return line ? "Stagger +2; speed -4." : "A firm strike with a slower step.";
    case 20: return line ? "Attack +2; reach +6." : "A steady short-lane bow.";
    case 37: return line ? "Guard +2; HP +8; speed -2." : "Flexible kilnwork padding.";
    case 53: return line ? "HP +4; speed +4." : "Light porous walking soles.";
    case 67: return line ? "Guard +1; stagger +1." : "A firm belt for steady work.";
    case 85: return line ? "Speed +2; power wait -3." : "A softly vibrating ring.";
    case 5: return line ? "Attack +2; reach +2." : "A broad terrace-work sword.";
    case 6: return line ? "No breathing meter or route permission." : "An optional underwater sidegrade.";
    case 13: return line ? "No breathing meter or route permission." : "An optional underwater sidegrade.";
    case 38: return line ? "No breathing meter or route permission." : "An optional underwater sidegrade.";
    case 54: return line ? "No breathing meter or route permission." : "An optional underwater sidegrade.";
    case 68: return line ? "No breathing meter or route permission." : "An optional underwater sidegrade.";
    case 86: return line ? "No breathing meter or route permission." : "An optional underwater sidegrade.";
    case 21: return line ? "Speed +4; arrow range +8." : "A light bow for the returning road.";
    case 39: return line ? "Defense +3; health +4; speed -2." : "A steady layer for familiar paths.";
    case 55: return line ? "Speed +4; roll cooldown -2." : "Easy steps over the homeward boards.";
    case 69: return line ? "Health +4; power cooldown -3." : "Carry the last reed delivery gently.";
    case 87: return line ? "Guard +1; speed -2; power -1." : "Stagger +1 with a patient step.";
    case 7: return line ? "Walking speed -2." : "Attack +1; reach +1; stagger +1.";
    case 14: return line ? "Health +4; reach +2; speed -2." : "A lance with a padded grip.";
    case 56: return line ? "Health +8; roll -1; speed -2." : "Soft soles for sheltered paths.";
    case 88: return line ? "Power wait -5; speed -2." : "A ring that catches the quiet.";
    case 40: return line ? "Walking speed -4." : "Defense +1; health +16.";
    case 89: return line ? "Walking speed -4." : "Roll wait -1; power wait -4.";
    default: return "";
    }
}
