/* Original Emberbond pixel art, generated by assets/generate_assets.py. */
#ifndef EMBERBOND_ASSETS_H
#define EMBERBOND_ASSETS_H
enum { BACK_VILLAGE, BACK_FOREST, BACK_TEMPLE, BACK_BOSS, BACK_TITLE, BACK_COUNT };
enum {
  SPR_HERO_DOWN_0,
  SPR_HERO_DOWN_1,
  SPR_HERO_UP_0,
  SPR_HERO_UP_1,
  SPR_HERO_LEFT_0,
  SPR_HERO_LEFT_1,
  SPR_HERO_RIGHT_0,
  SPR_HERO_RIGHT_1,
  SPR_FOX_0,
  SPR_FOX_1,
  SPR_LEAF_0,
  SPR_LEAF_1,
  SPR_SLIME_0,
  SPR_SLIME_1,
  SPR_ELDER,
  SPR_HEART_FULL,
  SPR_HEART_EMPTY,
  SPR_FLAME_0,
  SPR_FLAME_1,
  SPR_PROJECTILE,
  SPR_COUNT
};
extern const unsigned short game_palette[256];
#define EMBERBOND_POLISHED_ART 1
#define FOREGROUND_CANOPY_COUNT 6
/* Direction order: down, up, left, right. Frame 0 is the idle pose. */
extern const unsigned char hero_frames[4][4][256];
extern const unsigned char companion_frames[2][4][256];
extern const unsigned char companion_direction_frames[2][4][4][256];
extern const unsigned char hero_shadow[256];
extern const unsigned char boss_shadow[512];
typedef struct { short x,y; unsigned char room; } ForegroundCanopy;
extern const ForegroundCanopy foreground_canopies[FOREGROUND_CANOPY_COUNT];
extern const unsigned char foreground_canopy_data[FOREGROUND_CANOPY_COUNT][1024];
extern const unsigned char background_village[38400];
extern const unsigned char background_forest[38400];
extern const unsigned char background_temple[38400];
extern const unsigned char background_boss[38400];
extern const unsigned char background_title[38400];
extern const unsigned char * const backgrounds[BACK_COUNT];
extern const unsigned char sprite_data[SPR_COUNT][256];
extern const unsigned char boss_data[1024];

/* Named palette indices, including colors useful for HUD and overlays. */
#define PAL_TRANSPARENT 0
#define PAL_INK 1
#define PAL_DEEP 2
#define PAL_NIGHT 3
#define PAL_SLATE 4
#define PAL_FOG 5
#define PAL_SILVER 6
#define PAL_WHITE 7
#define PAL_PINE0 8
#define PAL_PINE1 9
#define PAL_PINE2 10
#define PAL_PINE3 11
#define PAL_PINE4 12
#define PAL_PINE5 13
#define PAL_MINT 14
#define PAL_GRASS0 15
#define PAL_GRASS1 16
#define PAL_GRASS2 17
#define PAL_GRASS3 18
#define PAL_GRASS4 19
#define PAL_DIRT0 20
#define PAL_DIRT1 21
#define PAL_DIRT2 22
#define PAL_DIRT3 23
#define PAL_DIRT4 24
#define PAL_WOOD0 25
#define PAL_WOOD1 26
#define PAL_WOOD2 27
#define PAL_WOOD3 28
#define PAL_WOOD4 29
#define PAL_WOOD5 30
#define PAL_STONE0 31
#define PAL_STONE1 32
#define PAL_STONE2 33
#define PAL_STONE3 34
#define PAL_STONE4 35
#define PAL_STONE5 36
#define PAL_ROSE0 37
#define PAL_ROSE1 38
#define PAL_ROSE2 39
#define PAL_ROSE3 40
#define PAL_ROSE4 41
#define PAL_ROSE5 42
#define PAL_GOLD0 43
#define PAL_GOLD1 44
#define PAL_GOLD2 45
#define PAL_GOLD3 46
#define PAL_GOLD4 47
#define PAL_FIRE0 48
#define PAL_FIRE1 49
#define PAL_FIRE2 50
#define PAL_FIRE3 51
#define PAL_WATER0 52
#define PAL_WATER1 53
#define PAL_WATER2 54
#define PAL_WATER3 55
#define PAL_WATER4 56
#define PAL_BLUE0 57
#define PAL_BLUE1 58
#define PAL_BLUE2 59
#define PAL_BLUE3 60
#define PAL_SKIN0 61
#define PAL_SKIN1 62
#define PAL_SKIN2 63
#define PAL_PURPLE0 64
#define PAL_PURPLE1 65
#define PAL_PURPLE2 66
#define PAL_PURPLE3 67
#define PAL_FLOWER0 68
#define PAL_FLOWER1 69
#define PAL_MOSS0 70
#define PAL_MOSS1 71
#define PAL_MOSS2 72
#define PAL_MOSS3 73
#define PAL_EMBER 74
#define PAL_HEART 75
#define PAL_HEARTLIGHT 76
#define PAL_SHADOW 77
#define PAL_TEAL0 78
#define PAL_TEAL1 79
#define PAL_TEAL2 80
#define PAL_CLOUD 81
#define PAL_DUSK0 82
#define PAL_DUSK1 83
#define PAL_DUSK2 84
#define PAL_DUSK3 85
#define PAL_DUSK4 86
#define PAL_SUN 87
#define PAL_LEAFLIGHT 88
#define PAL_LEAFWARM 89
#define PAL_GRASSLIT 90
#define PAL_GRASSGOLD 91
#define PAL_PLASTER 92
#define PAL_ROOFSHINE 93
#define PAL_SHADOWSOFT 94
#define PAL_BARKLIGHT 95
#define PAL_WATERGLEAM 96
#define PAL_BG_SUNLIT_PINE0 97
#define PAL_BG_SUNLIT_PINE1 98
#define PAL_BG_SUNLIT_PINE2 99
#define PAL_BG_SUNLIT_PINE3 100
#define PAL_BG_SUNLIT_PINE4 101
#define PAL_BG_SUNLIT_PINE5 102
#define PAL_BG_SUNLIT_LEAFLIGHT 103
#define PAL_BG_SUNLIT_LEAFWARM 104
#define PAL_BG_SUNLIT_GRASS0 105
#define PAL_BG_SUNLIT_GRASS1 106
#define PAL_BG_SUNLIT_GRASS2 107
#define PAL_BG_SUNLIT_GRASS3 108
#define PAL_BG_SUNLIT_GRASS4 109
#define PAL_BG_SUNLIT_GRASSLIT 110
#define PAL_BG_SUNLIT_GRASSGOLD 111
#define PAL_BG_SUNLIT_DIRT0 112
#define PAL_BG_SUNLIT_DIRT1 113
#define PAL_BG_SUNLIT_DIRT2 114
#define PAL_BG_SUNLIT_DIRT3 115
#define PAL_BG_SUNLIT_DIRT4 116
#define PAL_BG_SUNLIT_STONE0 117
#define PAL_BG_SUNLIT_STONE1 118
#define PAL_BG_SUNLIT_STONE2 119
#define PAL_BG_SUNLIT_STONE3 120
#define PAL_BG_SUNLIT_STONE4 121
#define PAL_BG_SUNLIT_STONE5 122
#define PAL_BG_SUNLIT_MOSS0 123
#define PAL_BG_SUNLIT_MOSS1 124
#define PAL_BG_SUNLIT_MOSS2 125
#define PAL_BG_SUNLIT_MOSS3 126
#define PAL_BG_SUNLIT_WOOD1 127
#define PAL_BG_SUNLIT_WOOD2 128
#define PAL_BG_SUNLIT_WOOD3 129
#define PAL_BG_SUNLIT_WOOD4 130
#define PAL_BG_SUNLIT_BARKLIGHT 131
#define PAL_BG_SUNLIT_PLASTER 132
#define PAL_BG_SUNLIT_SHADOW 133
#define PAL_BG_SUNLIT_SHADOWSOFT 134
#define PAL_BG_SUNLIT_WATER0 135
#define PAL_BG_SUNLIT_WATER1 136
#define PAL_BG_SUNLIT_WATER2 137
#define PAL_BG_SUNLIT_WATER3 138
#define PAL_BG_SUNLIT_WATER4 139
#define PAL_BG_SUNLIT_WATERGLEAM 140
#define PAL_BG_TEMPLE_STONE0 141
#define PAL_BG_TEMPLE_STONE1 142
#define PAL_BG_TEMPLE_STONE2 143
#define PAL_BG_TEMPLE_STONE3 144
#define PAL_BG_TEMPLE_STONE4 145
#define PAL_BG_TEMPLE_STONE5 146
#define PAL_BG_TEMPLE_NIGHT 147
#define PAL_BG_TEMPLE_MOSS0 148
#define PAL_BG_TEMPLE_MOSS1 149
#define PAL_BG_TEMPLE_GOLD0 150
#define PAL_BG_TEMPLE_GOLD1 151
#define PAL_BG_TEMPLE_GOLD2 152
#define PAL_BG_TEMPLE_SHADOW 153
#define PAL_BG_TWILIGHT_NIGHT 154
#define PAL_BG_TWILIGHT_DUSK0 155
#define PAL_BG_TWILIGHT_DUSK1 156
#define PAL_BG_TWILIGHT_DUSK2 157
#define PAL_BG_TWILIGHT_DUSK3 158
#define PAL_BG_TWILIGHT_DUSK4 159
#define PAL_BG_TWILIGHT_FOG 160
#define PAL_BG_TWILIGHT_PURPLE1 161
#define PAL_BG_TWILIGHT_WATER0 162
#define PAL_BG_TWILIGHT_WATER1 163
#define PAL_BG_TWILIGHT_WATER2 164
#define PAL_BG_TWILIGHT_WATER3 165
#define PAL_BG_TWILIGHT_WATER4 166
#define PAL_BG_TWILIGHT_STONE0 167
#define PAL_BG_TWILIGHT_STONE1 168
#define PAL_BG_TWILIGHT_STONE2 169
#define PAL_BG_TWILIGHT_STONE3 170
#define PAL_BG_TWILIGHT_STONE4 171
#define PAL_BG_TWILIGHT_PINE1 172
#define PAL_BG_TWILIGHT_PINE2 173
#define PAL_BG_TWILIGHT_PINE3 174
#define PAL_BG_TWILIGHT_PINE4 175
#define PAL_BG_TWILIGHT_PINE5 176
#define PAL_BG_TWILIGHT_LEAFLIGHT 177

#endif
