#!/usr/bin/env python3
"""Byte-exact old B versus candidate collision/draw/field/gameplay differential."""
import argparse,hashlib,json,os,subprocess,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];p=argparse.ArgumentParser();p.add_argument('--candidate',type=Path,default=ROOT);p.add_argument('--output',type=Path,required=True);a=p.parse_args();out=a.output.resolve();out.mkdir(parents=True,exist_ok=False)
base=ROOT/'build/return-bringup-b-source';candidate=a.candidate.resolve();modules=['return_legacy_powers','advanced_powers','regional_powers','northern_powers','southern_powers','northern_power_art','southern_power_art','creatures','creature_data','assets'];flags=['-std=c99','-O1','-g','-Wall','-Wextra','-Werror','-Wno-misleading-indentation','-pedantic'];sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();results={}
for kind,source,extra in [('baseline',base,[]),('candidate',candidate,[]),('candidate-asan',candidate,['-fsanitize=address,undefined','-fno-omit-frame-pointer','-fno-pie','-no-pie'])]:
 folder=out/kind;folder.mkdir();north=folder/'northern_powers.c';north.write_text((source/'src/northern_powers.c').read_text()+'''\nint collision_test_clear(int x,int y,int tx,int ty){return clear_segment(x,y,tx,ty);}\nvoid collision_test_draw(int x,int y,int tx,int ty){draw_line(x,y,tx,ty);}\nvoid collision_test_field(int x,int y,int tx,int ty,ReturnLegacyEmit emit,void*context){field_line(emit,context,x,y,tx,ty);}\n''');south=folder/'southern_powers.c';south.write_text((source/'src/southern_powers.c').read_text()+'''\nint collision_test_s_clear(int x,int y,int tx,int ty){return clear(x,y,tx,ty);}\nint collision_test_s_draw(int x,int y,int tx,int ty,unsigned initial){draw_count=(unsigned char)initial;return draw_line(x,y,tx,ty);}\nint collision_test_s_field(int x,int y,int tx,int ty,unsigned initial,ReturnLegacyEmit emit,void*context){FieldExport f={emit,context,initial};return field_line(&f,x,y,tx,ty);}\n''');exe=folder/'differential';sources=[ROOT/'tests/return_southern_collision_differential.c']+[north if m=='northern_powers' else south if m=='southern_powers' else source/'src'/f'{m}.c' for m in modules]
 subprocess.run(['cc',*flags,*extra,'-I'+str(source/'src'),'-I'+str(ROOT/'tests'),*map(str,sources),'-o',str(exe)],check=True)
 trace=folder/'trace.bin'
 with trace.open('wb')as f:subprocess.run([str(exe)],stdout=f,check=True,env=dict(os.environ,ASAN_OPTIONS='detect_leaks=0:halt_on_error=1',UBSAN_OPTIONS='halt_on_error=1'))
 results[kind]={'sha256':sha(trace),'bytes':trace.stat().st_size,'sources':{str(s):sha(s)for s in sources}};print(kind,results[kind]['sha256'],results[kind]['bytes'],flush=True)
assert len({v['sha256']for v in results.values()})==1,'original-versus-candidate behavioral/pixel trace mismatch'
report={'byte_exact':True,'direct_ray_cases':2*2*6*65*65+2*6*13*3,'dynamic_cast_frames':19*4*4*96,'no_native_timing_claim':True,'results':results};(out/'report.json').write_text(json.dumps(report,indent=2)+'\n')
