#!/usr/bin/env python3
"""Validate authored source and generate only the eight enabled C ROM rows."""
import json
from pathlib import Path
from validate_catalog import load_json, validate
ROOT = Path(__file__).resolve().parent
OUT = ROOT.parent.parent / 'src' / 'creature_data.c'

def generate():
    catalog = load_json(ROOT / 'catalog.json')
    errors = validate(catalog, load_json(ROOT / 'identity-lock.json'))
    if errors:
        raise ValueError('\n'.join(errors))
    enabled = json.loads((ROOT / 'enabled.json').read_text())
    ids = enabled['enabled_form_ids']
    if ids != [1, 2, 4, 5, 7, 8, 10, 11]:
        raise ValueError('Only the reviewed eight-form slice is enabled')
    phases = {p: i for i, p in enumerate(catalog['phase_order'])}
    caps = {p: 1 << i for i, p in enumerate(catalog['field_capabilities'])}
    slots = {s['id']: s for s in catalog['slots']}
    forms = [f for f in catalog['forms'] if f['id'] in ids]
    evolutions = [e for e in catalog['evolutions'] if e['from'] in ids and e['to'] in ids]
    if [[e['from'], e['to']] for e in evolutions] != enabled['enabled_evolutions']:
        raise ValueError('Enabled edges differ from reviewed evolution graph')
    out = ['/* Generated by assets/creatures/generate_data.py. Do not edit. */', '#include "creatures.h"', '',
           'const FormId creature_legacy_forms[4] = {1, 4, 7, 10};',
           'const CreatureForm creature_forms[CREATURE_ENABLED_COUNT] = {']
    learns = []
    for f in forms:
        s = slots[f['id']]
        edge = next((i for i,e in enumerate(evolutions) if e['from']==f['id']), None)
        values = [f['id'], int(s['family_id'][1:]), phases[f['phase']], int(f['polarity']=='yang'), s['tier'], int(s['rarity']=='legendary')]
        stats = ', '.join(str(f['stats'][k]) for k in ['vitality','power','guard','focus','haste'])
        out.append('    {%s, {%s}, %d, 0x%08xu, %d, %d, %d, %d, %d, 0, %d, 1},' % (
            ', '.join(map(str,values)), stats, f['signature_ability'], sum(caps[x] for x in f['field_caps']),
            f['id'],len(learns),len(f['learnset']),int(edge is not None),edge or 0,f['id']))
        learns.extend(f['learnset'])
    out += ['};', '', 'const CreatureLearn creature_learnsets[12] = {']
    out += ['    {%d, %d},' % (x['level'],x['ability_id']) for x in learns]
    out += ['};', '', 'const CreatureEvolution creature_evolutions[4] = {']
    gates = {'grove_clear':1, 'sky_clear':2, 'core_clear':4}
    trials = {'restore_hearth':1, 'restore_canopy':2, 'mend_wind_loom':4, 'raise_amber_arch':8}
    out += ['    {%d, %d, %d, %d, %d, %d},' % (e['from'],e['to'],e['min_level'],e['min_bond'],trials[e['required_trial']],gates[e['required_gate']]) for e in evolutions]
    out += ['};', '', 'const CreatureAbility creature_abilities[8] = {']
    abilities = [a for a in catalog['abilities'] if a['id'] <= 8]
    out += ['    {%d, %d, %d, 0x%08xu},' % (a['id'],phases[a['phase']],a['cooldown_updates'],sum(caps[x] for x in a['field_caps'])) for a in abilities]
    out += ['};', '', 'const char *creatures_name(unsigned form_id) {', '    switch (form_id) {']
    out += ['    case %d: return %s;' % (f['id'],json.dumps(f['name'])) for f in forms]
    out += ['    default: return "Unavailable form";', '    }', '}', '', 'const char *creatures_ability_name(unsigned ability_id) {', '    switch (ability_id) {']
    out += ['    case %d: return %s;' % (a['id'],json.dumps(a['name'])) for a in abilities]
    out += ['    default: return "No command";', '    }', '}', '']
    return '\n'.join(out)

if __name__ == '__main__':
    import sys
    text = generate()
    if '--check' in sys.argv:
        if OUT.read_text() != text:
            raise SystemExit('creature_data.c differs from authored catalog; regenerate it')
        print('Validated eight enabled forms, four edges, and deterministic ROM data')
    else:
        OUT.write_text(text)
        print(OUT)
