#!/usr/bin/env python3
"""Deterministic data-only equipment catalog. No runtime/content fallback IDs."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = Path(__file__).with_name('catalog.json')
TARGET = ROOT / 'src/equipment_data.c'
IDS = [1, 2, 9, 10, 17, 18, 33, 34, 49, 50, 65, 81, 82, 3, 11, 19, 35, 51, 83]
SLOTS = ['weapon', 'body', 'boots', 'belt', 'ring']
STATS = ['attack_q4', 'defense_q4', 'hp_q4', 'speed_q8_delta',
         'roll_reduction', 'power_reduction', 'reach_px', 'stagger']


def generate():
    data = json.loads(SOURCE.read_text())
    items, weapons = data['items'], data['weapon_classes']
    assert [x['id'] for x in items] == IDS
    assert [x['id'] for x in weapons] == [1, 2, 3]
    assert data['reward_sources'] == [dict(source_id=i, item_id=n) for i, n in enumerate(IDS)]
    lines = ['/* Generated by assets/equipment/generate_data.py; do not hand edit. */',
             '#include "equipment.h"', '',
             'const EquipmentItemId equipment_authored_ids[EQUIPMENT_AUTHORED_COUNT] = {',
             '    ' + ', '.join(map(str, IDS)) + '', '};', '',
             'const EquipmentDefinition equipment_definitions[EQUIPMENT_DEFINITION_CAPACITY] = {']
    for x in items:
        assert x['unique'] is True and x['max_rank'] == 0
        assert set(x['stats']) == set(STATS)
        for k in STATS:
            lo, hi = data['stat_bounds'][k]
            assert type(x['stats'][k]) is int and lo <= x['stats'][k] <= hi
        assert (x['slot'] == 'weapon') == ('weapon_class' in x)
        assert x['slot'] == 'weapon' or not x['stats']['reach_px']
        assert bool(x.get('protected')) == (x['id'] == 1)
        weapon = {'sword': 1, 'lance': 2, 'bow': 3}.get(x.get('weapon_class'), 0)
        stats = ', '.join(str(x['stats'][k]) for k in STATS)
        lines.append('    [%d] = {%d, %d, %d, %d, 255, {0, 0}, {%s}},' %
                     (x['id'], x['id'], SLOTS.index(x['slot']), weapon,
                      int(x.get('protected', False)), stats))
    lines += ['};', '', 'const EquipmentWeapon equipment_weapons[4] = {']
    for w in weapons:
        moves = []
        for m in w['moves']:
            values = [m[k] for k in ['windup', 'active', 'recovery', 'damage_q4', 'reach_px', 'half_width_px']]
            assert all(type(v) is int and 1 <= v <= 255 for v in values)
            moves.append('{' + ', '.join(map(str, values)) + '}')
        assert 1 <= len(moves) <= 3
        moves += ['{0, 0, 0, 0, 0, 0}'] * (3 - len(moves))
        fields = [w['id'], len(w['moves']), w['combo_window'], w['buffer'], w['lunge_q8'],
                  w.get('projectile_speed_q8', 0), w.get('charge_min_updates', 0),
                  w.get('charge_max_updates', 0), w.get('max_live_arrows', 0), 0]
        assert w.get('field_caps', []) == []
        lines.append('    [%d] = {%s, {%s}},' % (w['id'], ', '.join(map(str, fields)), ', '.join(moves)))
    lines += ['};', '', 'const char *equipment_name(unsigned id) {', '    switch (id) {']
    for x in items:
        lines.append('    case %d: return %s;' % (x['id'], json.dumps(x['name'])))
    lines += ['    default: return "Empty";', '    }', '}', '',
              'const char *equipment_description(unsigned id, unsigned line) {',
              '    if (line > 1) return "";', '    switch (id) {']
    for x in items:
        assert len(x['description']) == 2
        a, b = map(json.dumps, x['description'])
        lines.append('    case %d: return line ? %s : %s;' % (x['id'], b, a))
    lines += ['    default: return "";', '    }', '}', '']
    result = '\n'.join(lines)
    assert len(result.encode()) < 32768
    return result


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--check', action='store_true')
    args = p.parse_args()
    result = generate()
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != result:
            raise SystemExit('equipment data is stale; run assets/equipment/generate_data.py')
        print('equipment data: deterministic and current')
    else:
        TARGET.write_text(result)
        print('wrote', TARGET.relative_to(ROOT))


if __name__ == '__main__':
    main()
