#!/usr/bin/env python3
"""Deterministic data-only equipment catalog. No runtime/content fallback IDs."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = Path(__file__).with_name('catalog.json')
TARGET = ROOT / 'src/equipment_data.c'
RELEASED = SOURCE.with_name('released-v6.json')
RELEASED_SHA256 = '9aa8152c04060bc023803cf3adb7f1424fab0da2e5b0dc564f3935527fde4db4'
# Persistent source order: never insert into the published sources 0..18.
LEGACY_IDS = [1, 2, 9, 10, 17, 18, 33, 34, 49, 50, 65, 81, 82, 3, 11, 19, 35, 51, 83]
SOUTHERN_IDS = [4, 12, 36, 52, 66, 84]
MAGMA_IDS = [20, 37, 53, 67, 85, 5]
UNDERWATER_IDS = [6, 13, 38, 54, 68, 86]
RETURN_IDS = [21, 39, 55, 69, 87]
HORIZONS_IDS = [7, 14, 56, 88]
COVENANT_IDS = [40, 89]
RELEASED_V7 = SOURCE.with_name('released-v7.json')
RELEASED_V7_SHA256 = '8f0741e4b24469a7444e9bf62476b1d53d27c587df6cb98b875ef80257d853ab'
IDS = LEGACY_IDS + SOUTHERN_IDS + MAGMA_IDS + UNDERWATER_IDS + RETURN_IDS + HORIZONS_IDS + COVENANT_IDS
HORIZONS_CATALOG_SHA256 = 'da7acb332f10967d9fbf10bf2c75b5670025c0b88d94053a35c2e2f0a3a4d62a'
SLOTS = ['weapon', 'body', 'boots', 'belt', 'ring']
STATS = ['attack_q4', 'defense_q4', 'hp_q4', 'speed_q8_delta',
         'roll_reduction', 'power_reduction', 'reach_px', 'stagger']


def generate():
    data = json.loads(SOURCE.read_text())
    items, weapons = data['items'], data['weapon_classes']
    blob = RELEASED.read_bytes()
    assert hashlib.sha256(blob).hexdigest() == RELEASED_SHA256, 'released equipment snapshot changed'
    old = json.loads(blob)
    assert items[:len(old['items'])] == old['items'], 'released equipment definitions changed'
    assert data['reward_sources'][:len(old['reward_sources'])] == old['reward_sources'], 'released equipment source mappings changed'
    assert all(data[key] == value for key, value in old.items()
               if key not in ('items', 'reward_sources')), 'released equipment rules changed'
    v7_blob = RELEASED_V7.read_bytes()
    assert hashlib.sha256(v7_blob).hexdigest() == RELEASED_V7_SHA256, 'released revision7 equipment snapshot changed'
    v7 = json.loads(v7_blob)
    assert items[:42] == v7['items'], 'released revision7 equipment definitions changed'
    assert data['reward_sources'][:42] == v7['reward_sources'], 'released revision7 equipment source mappings changed'
    assert all(data[key] == value for key, value in v7.items()
               if key not in ('items', 'reward_sources')), 'released revision7 equipment rules changed'
    prior = dict(data, items=items[:46], reward_sources=data['reward_sources'][:46])
    canonical = json.dumps(prior, sort_keys=True, separators=(',', ':'), ensure_ascii=False).encode()
    assert hashlib.sha256(canonical).hexdigest() == HORIZONS_CATALOG_SHA256, 'accepted revision8 equipment definitions or rules changed'
    for item, name, slot, bonuses in zip(items[46:], ['Wayfarer Coat', 'Porchlight Ring'],
            ['body', 'ring'], [[0,1,16,-4,0,0,0,0], [0,0,0,-4,1,4,0,0]]):
        assert item['name'] == name and item['slot'] == slot, 'Covenants equipment identity changed'
        assert [item['stats'].get(k) for k in STATS] == bonuses, 'Covenants equipment sidegrade changed'
    assert [x['id'] for x in items] == IDS
    assert [x['id'] for x in weapons] == [1, 2, 3]
    assert data['reward_sources'] == [dict(source_id=i, item_id=n) for i, n in enumerate(IDS)]
    lines = ['/* Generated by assets/equipment/generate_data.py; do not hand edit. */',
             '#include "equipment.h"', '',
             'const EquipmentItemId equipment_authored_ids[EQUIPMENT_AUTHORED_COUNT] = {',
             '    ' + ', '.join(map(str, IDS)) + '', '};', '',
             'const EquipmentDefinition equipment_definitions[EQUIPMENT_DEFINITION_CAPACITY] = {']
    for x in items:
        assert x['unique'] is True and x['max_rank'] == 0
        assert set(x['stats']) == set(STATS)
        for k in STATS:
            lo, hi = data['stat_bounds'][k]
            assert type(x['stats'][k]) is int and lo <= x['stats'][k] <= hi
        assert (x['slot'] == 'weapon') == ('weapon_class' in x)
        assert x['slot'] == 'weapon' or not x['stats']['reach_px']
        assert bool(x.get('protected')) == (x['id'] == 1)
        weapon = {'sword': 1, 'lance': 2, 'bow': 3}.get(x.get('weapon_class'), 0)
        stats = ', '.join(str(x['stats'][k]) for k in STATS)
        lines.append('    [%d] = {%d, %d, %d, %d, 255, {0, 0}, {%s}},' %
                     (x['id'], x['id'], SLOTS.index(x['slot']), weapon,
                      int(x.get('protected', False)), stats))
    lines += ['};', '', 'const EquipmentWeapon equipment_weapons[4] = {']
    for w in weapons:
        moves = []
        for m in w['moves']:
            values = [m[k] for k in ['windup', 'active', 'recovery', 'damage_q4', 'reach_px', 'half_width_px']]
            assert all(type(v) is int and 1 <= v <= 255 for v in values)
            moves.append('{' + ', '.join(map(str, values)) + '}')
        assert 1 <= len(moves) <= 3
        moves += ['{0, 0, 0, 0, 0, 0}'] * (3 - len(moves))
        fields = [w['id'], len(w['moves']), w['combo_window'], w['buffer'], w['lunge_q8'],
                  w.get('projectile_speed_q8', 0), w.get('charge_min_updates', 0),
                  w.get('charge_max_updates', 0), w.get('max_live_arrows', 0), 0]
        assert w.get('field_caps', []) == []
        lines.append('    [%d] = {%s, {%s}},' % (w['id'], ', '.join(map(str, fields)), ', '.join(moves)))
    lines += ['};', '', 'const char *equipment_name(unsigned id) {', '    switch (id) {']
    for x in items:
        lines.append('    case %d: return %s;' % (x['id'], json.dumps(x['name'])))
    lines += ['    default: return "Empty";', '    }', '}', '',
              'const char *equipment_description(unsigned id, unsigned line) {',
              '    if (line > 1) return "";', '    switch (id) {']
    for x in items:
        assert len(x['description']) == 2
        a, b = map(json.dumps, x['description'])
        lines.append('    case %d: return line ? %s : %s;' % (x['id'], b, a))
    lines += ['    default: return "";', '    }', '}', '']
    result = '\n'.join(lines)
    assert len(result.encode()) < 32768
    return result


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--check', action='store_true')
    args = p.parse_args()
    result = generate()
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != result:
            raise SystemExit('equipment data is stale; run assets/equipment/generate_data.py')
        print('equipment data: deterministic and current')
    else:
        TARGET.write_text(result)
        print('wrote', TARGET.relative_to(ROOT))


if __name__ == '__main__':
    main()
