#!/usr/bin/env python3
"""Emit developer-only Magma design artifacts. Never touches the game checkout."""
from pathlib import Path
import json, hashlib
ROOT=Path(__file__).resolve().parent
SOURCE=ROOT.parent/'adventure-legends-southern'
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
lock=json.loads((SOURCE/'assets/creatures/identity-lock.json').read_text())
cat=json.loads((SOURCE/'assets/creatures/catalog.json').read_text())
enabled=json.loads((SOURCE/'assets/creatures/enabled.json').read_text())
items=json.loads((SOURCE/'assets/equipment/catalog.json').read_text())
identity={x['id']:x for x in lock['slots']}
# Each row: ID, name, silhouette, locomotion, role, signature name, geometry/behavior,
# startup, active, recovery, cooldown, max live objects, total damage Q4.
rows=[
(31,'Coalcoil','A low snail with a broad smiling muzzle, two blunt eyestalks and a sideways crescent shell; pale foot clearly separate from charcoal shell.','Foot ripples in four readable waves; shell rocks after the head stops.','Delayed lane crossing','Warm Thread','Draw a 40px ground thread after an 8-update warning; first crossing ends it. No through-wall segments.',8,36,12,90,1,16),
(32,'Emberhelix','A raised snail on a narrow long foot; its open spiral shell sits upright with a large triangular window and expressive face below.','Stretch, brace, pull the shell forward; spiral tips lag by one pose.','Two-point squeeze','Coil Clamp','Two hooked arcs close on a 32px pocket; a target is hit once across both arcs. The player can walk through.',12,16,16,120,2,24),
(33,'Hearthcrown','A long muscular snail with a flat fan-shaped shell held above its face on three connected shell ribs; large open spaces replace the earlier spiral.','Wide foot fans to anchor, then contracts into an unhurried glide.','Delayed directional denial','Crown Interval','Show three short spokes, then activate them in order; share a 32Q4 target budget across the whole cast. Gap remains visibly safe.',18,30,20,150,3,32),
(34,'Shardibex','A small round-nosed mountain goat with short straight stone horns, wide cloven feet and a tilted rectangular shoulder patch.','Quick paired hoof plants, head dip, rear-foot catch-up.','Short-range interrupt','Heel Knock','A narrow 22px stomp cone interrupts eligible ordinary foes; no boss displacement or terrain mutation.',6,8,16,90,1,20),
(35,'Bracehorn','A low broad-shouldered goat with huge outward U-curved horns enclosing its face, short hindquarters and distinctly spread forehooves.','Three-beat brace and short forward shuffle; head stays level.','Commitment counter','Brace Reply','Visible frontal bracing arc catches one eligible ordinary contact attack, then replies; expiry gives no damage and no invulnerability.',12,24,18,120,1,24),
(36,'Spanram','A tall long-legged ram with two high buttress horns joining above its brow, a narrow waist and two strong negative-space arches.','High deliberate diagonal hoof steps; horns sway opposite hips.','Wide frontal stagger','Archfall','A visible overhead arch lands in a wide 44px frontal crescent after its warning. No temporary solid wall, crush or player push.',20,10,22,150,1,32),
(37,'Tuftpika','A tiny pika with long swept-back grass whiskers, round ears, a square leafy tail tuft and two high-set dark eyes.','Compact four-paw gallop, pause, whisker flick.','Precision hindrance','Burr Skip','One bouncing seed follows two 18px ground hops; first ordinary hit gets a short visible slow. Walls end the path.',8,18,12,90,1,16),
(38,'Rootmuffle','A low long-bodied pika with a broad root beard and two separated leafy shoulder mounds; its ears and living muzzle remain exposed.','Low belly-clear scamper; beard trails, then gathers beneath chin.','Narrow area hold','Root Hem','Two parallel 32px root lines leave a walkable central gap; crossing either gives one brief ordinary-root effect, never on a boss.',14,36,14,120,2,20),
(39,'Sporevault','An upright long-hindleg pika with a closed pinecone tail carried above its head and a tiny chest between large open arm spaces.','Crouch, tall hop, two-foot settle; tail opens only during casting.','Remote falling strike','Cone Drop','Aimed visible 12px landing marker within48px; one falling cone hits after16 updates, with line of sight checked at aim and impact.',16,6,18,120,1,24),
(40,'Chalklung','A living porous sponge with three soft lobed feet, one angled chimney and a friendly face on its lower flexible skirt.','Three-foot rocking walk; chimney compresses and rebounds as it breathes.','Stopping a charge','Mist Stop','A short square puff at28px arrests one eligible ordinary rush without pulling the player; one target hit per cast.',8,12,14,90,1,16),
(41,'Bellcup','A tall sponge with an inverted bell mouth, a long curved neck, broad two-lobed base and a face looking out beneath the rim.','Leans forward on the base, straightens neck, then draws the base underneath.','Vertical lane control','Cup Shower','A stationary narrow three-drop column falls at a visible marker; all drops share24Q4 maximum per target.',12,30,18,120,3,24),
(42,'Runnelribbon','A flat ribbon sponge with two raised breathing sails, four stub feet and a living face at one blunt leading corner.','Sideways inchworm fold, unfold and soft skirt sweep.','Lateral crossing interception','Ribbon Sweep','A45px lateral water band travels along one wall-checked segment; widens only after its first12px. Single target budget24Q4.',10,20,20,120,1,24),
(43,'Orelet','A round mole with a pale snout, narrow metallic digging nails and one smooth ore nodule at the tip of its very short tail.','Alternating outward forepaw scoops with its feet visibly above the ground.','Close approach interruption','Pick Tap','Two short alternating nail jabs; second occurs only if first misses, so one enemy cannot take both.',6,12,16,90,2,20),
(44,'Augermole','A long wedge-bodied mole whose broad serrated forepaws frame a low face; its body tapers into a small straight tail.','Wide shoulder crawl with nails swept behind during recovery.','Armor-window punish','Spiral Notch','A narrow28px corkscrew strike; deals ordinary Metal damage with bounded stagger on an already vulnerable target. No armor bypass.',14,8,22,120,1,28),
(45,'Pendulumole','An upright mole with long forearms, broad planted hindfeet and an elongated heavy tail curved into a counterweight loop.','Two hindfoot steps then tail counter-swing; face aims independently of arms.','Delayed flanking shot','Tail Pendulum','A short visible diagonal swing releases one18px lateral shard; swing and shard share24Q4, walls stop both.',16,20,16,120,2,24),
(46,'Ashkite','A planthopper with a broad kite-shaped shell, very short antennae, tucked legs and a visible round face below a shallow hood.','Tiny spring hop, side slip and four-foot landing.','Angled opener','Cinder Tilt','One26px diagonal dart from the chosen facing side, with a readable aiming blink; stops at first wall or enemy.',8,10,12,90,1,16),
(47,'Plumehopper','A tall long-legged hopper with a narrow upright plume, a pear-shaped abdomen and an open diamond between its rear legs.','High tucked-leg spring, upright hover beat and heel-first landing.','Cross-lane follow-through','Plume Cut','A narrow rising slash then a forward falling slash; shared24Q4 target cap, no auto-tracking after startup.',12,18,18,120,2,24),
(48,'Huskdrifter','A broad leaf-shaped hopper held horizontally beneath translucent folded shell sails, with a small face extending beyond their front edge.','Low skirt-like glide with visible occasional leg taps; not a permanent flight permission.','Protective interruption','Ash Screen','A stationary small screen consumes one ordinary hostile projectile, expires after40 updates, then makes a16Q4 outward puff. Boss beams unaffected.',14,40,18,120,1,16),
(95,'Screepeek','A stocky tapir with a short mobile trunk, small round ears, heavy hindquarters and three pale pebble pads along its shoulder.','Slow alternating four-foot stroll; trunk probes ahead on the idle beat.','Close sweeping attack','Gravel Sift','A short fan of three ground chips, sharing20Q4 per target; maximum travel30px and wall stops per chip.',10,12,12,90,3,20),
(96,'Stairtrunk','A long-trunked tapir with stepped flaring ears, high shoulders and low hindquarters, leaving a clear diagonal back silhouette.','Forefoot reach, trunk curl, broad rear step; ears fold on recovery.','Reliable reach tradeoff','Terrace Lift','A sequence of two rising28px wedges separated by a safe lateral gap; one hit per target across both, no forced boss movement.',16,20,20,120,2,24),
(97,'Mossmarch','A short six-legged caterpillar-like animal with a square muzzle, four separated moss cushions and a bare expressive brow.','Six legs ripple in three pairs while cushions squash in sequence.','Moving narrow pressure','Sprig March','One slow ground bud advances36px with a visible toe-like motion; it ends on first enemy or wall rather than lingering.',10,24,12,90,1,16),
(98,'Trellislong','A long high-arched six-legged crawler with an open lattice of connected moss ribs above its smooth living underside and wide face.','Three alternating leg pairs carry a traveling body arch, never a static stretched base sprite.','Bent approach control','Trellis Bend','Two connected ground segments form one chosen L-shaped path, capped48px total; one hit per target and no wall penetration.',14,30,16,120,2,24),
(99,'Dripurchin','A low sea-urchin-like animal with a soft visible face, five blunt movable spines and three rounded tube feet.','Rotates its feet without rotating its face, then bobs with gathered droplets.','Radial safe-distance lesson','Bead Step','Three small outward beads leave large gaps; one enemy can receive only16Q4 across the fan. No homing.',10,14,12,90,3,16),
(100,'Dewmedusa','A tall soft-bodied urchin with its five spines opened into curved umbrella ribs and long joined tube-foot tassels; face hangs below the cap.','Gentle pulse-lift then trailing-foot settle; a grounded shadow makes its location legible.','Center-out reposition cue','Dewfold','An expanding five-lobed ring shows safe gaps before moving; edge-only24Q4 once per target, never a full-screen burst.',18,24,18,120,1,24),
]
family_specs=[
('F011',[31,32,33],'fire','yin',['store_heat'], 'Q30',38,'Receive the rescued hatchling after manually moving an insulated jar to the marked cool shelf; no heat power is needed to earn it.'),
('F012',[34,35,36],'earth','yang',['press_weight'], 'Q31',39,'Raise the pedestrian brace with its public handwheel and guide the young ibex along the open terrace; no weight power is needed.'),
('F013',[37,38,39],'wood','yin',['grow_roots'], 'M_FIELD_0',39,'Follow paired nibble marks to a sheltered plot; put its visibly displaced seed tray back without clearing the living hedge.'),
('F014',[40,41,42],'water','yang',['fill_basin','reveal_current'], 'M_FIELD_1',41,'Read the three ripple marks and manually unclog the public catch bowl; a sponge walks out of the dry side niche.'),
('F015',[43,44,45],'metal','yin',['draw_ore'], 'M_FIELD_2',40,'Return two visibly labeled loose ore samples to their matching shelf shapes; the mole leaves its inspection basket.'),
('F016',[46,47,48],'fire','yang',['turn_vane'], 'M_FIELD_3',39,'Set a public wind hood away from the seedling bed using its handle, then approach the hopper shelter.'),
('F036',[95,96],'earth','yin',['uncap_well'], 'M_FIELD_4',39,'Uncover a clearly marked shallow spring lip with its A-operated brush; broad tracks lead to the waiting tapir.'),
('F037',[97,98],'wood','yang',['reel_load'], 'M_FIELD_5',40,'Inspect the moving moss along a frayed drying-line guide; solve the manual two-hook return and invite the crawler.'),
('F038',[99,100],'water','yin',['tune_latch'], 'M_FIELD_6',41,'Finish the optional Listening Stones discovery commission, then open the indicated quiet catch. The urchin is visible behind the grille before release.'),
]
trials={
'F011': [('Three Cool Shelves', [38,40,42], 'Store heat from each of three numbered refractory jars, then park each at the matching safe shelf; never warm the seedling tray.',26,45),('One Hearth, Three Uses',[40,44], 'As form32, reuse one charged brick to dry clay, temper a tool and warm seedlings in that order, cooling it at a marked sink between uses; prove all three different outputs.',32,60)],
'F012': [('A Walkable Load',[39,43], 'Press three marked braces while each pedestrian side lane remains open; dragging a baffle into a walking lane invalidates only that attempt.',26,45),('The Unbroken Crossing',[39,44], 'As form35, brace the high and low supports from opposite landings and move the central slab between them without blocking the marked return loop.',32,60)],
'F013': [('Shelter the Roots',[39], 'Grow roots into two dry hedge ties while a third living opening stays clear; choose the low sheltered plot, not every green target.',26,45),('Scatter the Canopy',[39,40], 'Grow two elevated seed supports after manually opening the airflow hood; carry the marked seed tray by the open upper walkway.',26,45)],
'F014': [('Keep the Last Drop',[41], 'Reveal the feeding current, fill the catch bowl and close two leaks before draining the practice outlet; targets have distinct shapes.',26,45),('Share the Runnel',[39,41], 'Reveal both branch arrows and fill alternating receiving bowls without feeding the already-full trough; no timer or random rain.',26,45)],
'F015': [('True the Buried Seam',[40,41], 'Draw three sample pins out in the diagrammed direction while the protected pot is behind its baffle; each pin has an independent identity.',26,45),('Balance the Hanging Note',[40], 'Draw two counterweights to opposite marked rests until the hanging clapper clears both sides; the player can inspect its entire swing.',26,45)],
'F016': [('Lift the Warm Air',[39,44], 'Turn three hood vanes to lift a visible ribbon through upper outlets without blowing on the seedling bed.',26,45),('Settle the Ash',[39,40], 'Turn the hood down into a settling basket, open its safe side bypass and return the hood to still; visible ash clears rather than becoming a damage cloud.',26,45)],
'F036': [('Find the Cold Seam',[39,41], 'Uncap three signposted spring mouths in separate pockets after observing their distinct bubbles; one dry inspection socket must be left closed.',26,45)],
'F037': [('The Cloth Stays Clear',[40,44], 'Reel the drying line through three marked hooks from different safe approaches while a wide worker passage remains unobstructed.',26,45)],
'F038': [('The Quiet Chord',[38,41], 'Tune three mechanically distinct catches after placing sound baffles on their pictogram rests; the source is geometry and vibration cues, not hearing acuity.',26,45)],
}
family_map={fid:(ids,phase,pol,caps,source,room,acq) for fid,ids,phase,pol,caps,source,room,acq in family_specs}
forms=[]; edges=[]; bindings=[]; families=[]
for fid,ids,phase,pol,caps,source,room,acq in family_specs:
 fcat=next(x for x in cat['families'] if x['id']==fid)
 families.append({'family_id':fid,'shape':fcat['shape'],'form_ids':ids,'initial_source':source,'initial_room':room,'acquisition':acq,'guaranteed':source.startswith('Q'),'branch_extra_source':f'M_BRANCH_{int(fid[1:])-13}' if fcat['shape']=='branch_three' else None})
 for k,(name,rooms,proof,lvl,bond) in enumerate(trials[fid],1):
  bindings.append({'family_id':fid,'local_trial_key':k,'wire_mask':1<<(k-1),'prerequisite_mask':1 if k==2 and fcat['shape']=='linear_three' else 0,'name':name,'rooms':rooms,'participant_from_forms':[ids[k-1]] if fcat['shape']=='linear_three' else [ids[0]],'environmental_proof':proof,'level_floor':lvl,'bond_floor':bond,'aid_index':40+len(bindings),'completion_context':'CALDERA_OPEN' if k==2 and fcat['shape']=='linear_three' else 'MAGMA_READY','requires_source':source,'same_instance_required':True})
 for a,b in fcat['planned_edges']:
  trialkey=2 if b==ids[-1] and len(ids)==3 else 1
  tr=next(t for t in bindings if t['family_id']==fid and t['local_trial_key']==trialkey)
  edges.append({'from':a,'to':b,'family_id':fid,'local_trial_key':trialkey,'required_mask':3 if identity[b]['tier']==3 else tr['wire_mask'],'min_level':tr['level_floor'],'min_bond':tr['bond_floor'],'context':tr['completion_context'],'sanctuary':True,'explicit_target_confirmation':True,'activation_gates':['historical_policy_isolation','multi_trial_subset_policy'] + (['third_tier_validation'] if identity[b]['tier']==3 else []) + (['branch_choice_and_second_copy'] if fcat['shape']=='branch_three' else [])})
for i,row in enumerate(rows):
 id,name,silhouette,motion,role,command,behavior,start,active,recover,cool,objs,damage=row
 ident=identity[id];fid=ident['family_id'];ids,phase,pol,caps,source,room,acq=family_map[fid]
 tier=ident['tier'];p=pol
 if id in (39,48): p='yang' if pol=='yin' else 'yin'
 fields=list(caps)
 if id==33: fields+=['ignite']
 if id in (35,36):fields+=['break_crack']
 incoming=next((e for e in edges if e['to']==id),None)
 lineage=[id];cur=id
 while (e:=next((e for e in edges if e['to']==cur),None)):
  cur=e['from'];lineage.insert(0,cur)
 statbase={'fire':[30,44,26,45,35],'earth':[44,33,43,30,30],'wood':[33,31,34,43,39],'water':[37,28,37,46,32],'metal':[32,45,38,32,33]}[phase]
 total={1:180,2:240,3:285}[tier]
 weights=[n+((total-180)//5) for n in statbase]
 forms.append({**ident,'name':name,'phase':phase,'polarity':p,'status':'design_only','runtime_enabled':False,'silhouette':silhouette,'locomotion':motion,'field_caps':fields,'field_role':f"Use {' + '.join(fields)} only on the chapter's explicit compatible tagged fixtures; phase alone grants no action.",'combat_role':role,'stats':dict(zip(['vitality','power','guard','focus','haste'],weights)),'stat_total':total,'signature_ability':43+i,'learnset':[{'ability_id':43+next(j for j,r in enumerate(rows) if r[0]==ancestor),'min_level':1 if ancestor==ids[0] else next(e['min_level'] for e in edges if e['to']==ancestor)} for ancestor in lineage],'command':{'name':command,'behavior':behavior,'timing_updates':{'startup':start,'active':active,'recovery':recover,'cooldown':cool},'max_live_objects':objs,'max_total_damage_q4_per_target':damage,'wall_checked':True,'player_invulnerability':False,'boss_control_effects':False},'acquisition':{'kind':'evolution' if incoming else 'guaranteed_quest' if source.startswith('Q') else 'typed_field','source':source,'room':room,'detail':acq if not incoming else f"Explicit {incoming['from']}→{id} choice after owning-family trial {incoming['local_trial_key']}; defer is unchanged.", 'repeatable_base':next(f['shape']=='branch_three' for f in families if f['family_id']==fid)},'evolution':incoming})
rooms=[
(38,'Kilnstep Commons',[480,320],'town','Rest, workshop courtyards, Q30 lesson, source kiosk and a visible mountain lift.'),
(39,'Pumice Terraces',[480,320],'field','Sheltered garden cells, branching uphill walk, Q31 brace lesson, five ecological encounters and rest.'),
(40,'Potters Walk',[240,160],'interior','Working drying hall with an open courtyard window; baffles, sample shelves and return line.'),
(41,'Cloudwell Grotto',[240,160],'interior','Cool seep-fed tube with skylight and dry ledges; spring and sound-baffle discoveries.'),
(42,'Intake Ledger',[240,160],'puzzle','Move an insulated heat brick around a cold dividing wall, charge it with STORE_HEAT and seat it at the marked receiver.'),
(43,'Breathing Vault',[240,160],'puzzle','Move a baffle and pressure shoe so the safe relief outlet remains clear; PRESS_WEIGHT seats the marked brace.'),
(44,'Return-Flue Gallery',[240,160],'puzzle','Combine heat routing and the weight brace, then strike a visible release pin using any ordinary weapon; safe lower route remains open.'),
(45,'Caldera Bell',[240,160],'boss','Redirect an oversealed civic kiln regulator; side lanes, heat-safe landing and a clearly warned coupling window.'),
]
roomlist=[{'id':id,'name':name,'dimensions':sz,'kind':kind,'purpose':purpose,'visit_byte':3,'visit_bit':id-38,'sanctuary':id in [38,39],'reset_available':kind!='town','unconditional_return':38 if id in [39,40] else 39 if id in [41,42] else id-1} for id,name,sz,kind,purpose in rooms]
# Every forward link is paired with a separately ungated retreat link; stage flags gate only progress.
links=[]
def link(a,b,gate):links.extend([{'from':a,'to':b,'requires':gate},{'from':b,'to':a,'requires':[]}])
link(38,39,[]);link(38,40,[]);link(39,41,[]);link(39,42,['Q30','Q31']);link(42,43,['Q32:1']);link(43,44,['Q32:3']);link(44,45,['Q32:7'])
links += [{'from':44,'to':39,'requires':['Q32:7']},{'from':45,'to':38,'requires':['Q32:15']}]
quests=[
{'id':30,'name':'A Hearth That Can Travel','kind':'teaching','mask':3,'objectives':['Move the cool insulated jar to its outlined shelf by hand','Fit the open public hood using A; speak with keeper Ressa'],'recruit':31,'gear_source':25,'rooms':[38],'requires':[]},
{'id':31,'name':'A Footpath for Everyone','kind':'teaching','mask':3,'objectives':['Raise the public handwheel brace','Guide the young goat along the open pedestrian route'],'recruit':34,'gear_source':None,'rooms':[39],'requires':[]},
{'id':32,'name':'Let the Mountain Breathe','kind':'main','mask':15,'allowed_prefixes':[0,1,3,7,15],'objectives':['Complete heat routing in42 with STORE_HEAT','Seat brace in43 with PRESS_WEIGHT','Combine both and release the tagged pin in44','Stop the regulator in45 and report to Ressa'],'recruit':None,'gear_source':None,'rooms':[42,43,44,45],'requires':['Q30','Q31']},
{'id':33,'name':'Pots Without Cracks','kind':'optional','mask':7,'objectives':['Read potter Nemi’s three shape-stamped drying tags','Use three distinct safe shelf/baffle configurations','Return the intact practice set, with no timed carrying segment'],'recruit':None,'gear_source':26,'rooms':[38,40],'requires':['Q30']},
{'id':34,'name':'The Last Cool Cup','kind':'optional','mask':3,'objectives':['Trace the seep via visible flow arrows','Open the bypass and fill the public basin without emptying the creature refuge'],'recruit':None,'gear_source':27,'rooms':[39,41],'requires':[]},
{'id':35,'name':'A Clear Way Home','kind':'optional','mask':3,'objectives':['Move the marked fallen screen off the walker’s low route','Open the return door from its safe outer approach'],'recruit':None,'gear_source':28,'rooms':[39,40],'requires':[]},
{'id':36,'name':'The Missing Chime','kind':'optional','mask':3,'objectives':['Follow the drawn vibration marks to the hanging counterweight','Use the public hook and free the clapper while its pedestrian lane stays open'],'recruit':None,'gear_source':29,'rooms':[38,40],'requires':[]},
{'id':37,'name':'A Seedbed Above the Smoke','kind':'optional','mask':7,'objectives':['Read gardener Omi’s wind-ribbon clue','Set the upper hood away from the marked seedbed','Carry the reusable seed tray to its clear landing and report'],'recruit':None,'gear_source':30,'rooms':[39,44],'requires':['Q32:3']},
]
comm={'key':'M_LISTENING_STONES','name':'Listening Stones','kind':'optional_discovery_commission','global_quest_id':None,'journal_states':'UNSEEN/ACTIVE/READY/CLAIMED derived from the typed discovery bits and M_FIELD_6, not a ninth global quest slot','rooms':[38,41],'steps':[{'bit':0,'name':'Hear the spring keeper’s request or inspect the illustrated sign in41; records the request'},{'bit':1,'name':'Move both sound baffles to the shape-marked rests; records the revealed niche','requires_mask':1},{'bit':2,'name':'Return the public clapper to its marked catch and reveal Dripurchin; records READY','requires_mask':3}],'discovery_byte':19,'allowed_prefixes':[0,1,3,7],'reward_source':'M_FIELD_6','retained_reward_form':99,'no_gear_claim_gate':True,'clues':['Five droplet-shaped indentations beside the grille','A visible moving face and repeated drawn vibration marks'],'completion':'Explicit invitation commits retained99+field source; request/ready remain available if the roster is full.'}
gear_defs=[(20,'Ventstring Bow','weapon','bow',{'attack_q4':2,'reach_px':6},25,30,'Less reach than Headland Bow and less attack than Tidewood Bow; never mandatory for a puzzle.'),(37,'Kilnweave Mail','body',None,{'defense_q4':2,'hp_q4':8,'speed_q8_delta':-2},26,33,'Trades Hearthscale guard/health for lighter speed loss; distinct mixed option.'),(53,'Pumice Boots','boots',None,{'speed_q8_delta':6},27,34,'Below Trail Boots speed; reserve this reward as an alternate early-source sidegrade, remove if native choice testing shows no reason to use.'),(67,'Bricklayer Belt','belt',None,{'defense_q4':1,'speed_q8_delta':-2,'stagger':1},28,35,'Trading movement and Woven health for limited defense/interruption.'),(85,'Quietnote Ring','ring',None,{'power_reduction':3,'speed_q8_delta':2},29,36,'Less cooldown benefit than Resonance; modest movement alongside it, within clamps.'),(5,'Terrace Sword','weapon','sword',{'attack_q4':2,'reach_px':2,'speed_q8_delta':-2},30,37,'Between attack and spacing, but slower than Ropeguard; balance review may replace this bounded stat vector.')]
# Ensure each item offers an actual tradeoff rather than a weaker existing item.
gear_defs[2]=(53,'Pumice Boots','boots',None,{'speed_q8_delta':4,'hp_q4':4},27,34,'Half Trail Boots speed with a quarter-heart reserve; gives up Deck Boots roll reduction.')
gear=[]
for id,name,slot,wclass,stats,source,q,cost in gear_defs:
 full={k:0 for k in items['stat_bounds']};full.update(stats)
 gear.append({'id':id,'name':name,'slot':slot,'weapon_class':wclass,'stats':full,'source_id':source,'quest_id':q,'tradeoff':cost,'required_for_progression':False,'status':'design_only'})
field=[]
for i,f in enumerate(families[2:]):field.append({'token':f'M_FIELD_{i}','family_id':f['family_id'],'base_form':f['form_ids'][0],'room':f['initial_room'],'region_byte':9,'bit':i,'requires':['entry','visit38',f"visit{f['initial_room']}"]+(['discovery19:7'] if i==6 else []),'retained_minimum':1,'aid_index':55+i,'inner_generic_reward_id':0})
branch=[]
for i,f in enumerate(families[2:6]):branch.append({'token':f'M_BRANCH_{i}','family_id':f['family_id'],'base_form':f['form_ids'][0],'room':f['initial_room'],'region_byte':16,'bit':i,'unlock':'The initial source is claimed and one of this family’s two evolved branches is currently retained; a marked second footprint/empty nest appears beside the original encounter.','first_receipt_retained_minimum':2,'distinct_instance_ids':True,'repeatable':True,'subsequent_reward_credit':False,'inner_generic_reward_id':0,'no_history_cloning':True,'reencounter_action':['F013: return a reusable seed tray to the second marked shelter','F014: manually open the second catch bowl’s safe spillway','F015: seat the public second sample basket under the ore chute','F016: set the secondary wind hood to its marked neutral shelter'][i]})
plan={
'schema_version':1,'scope':'DESIGN_ONLY_NOT_IN_ROM','runtime_enablement':False,'chapter':'Magma Mountain: Kilnstep / The Breathing Kiln','content_revision_proposal':5,'authored_against_revision':4,'exact_new_form_ids':list(range(31,49))+list(range(95,101)),'family_count':9,'new_form_count':24,
'baseline':{'enabled_form_ids':enabled['enabled_form_ids'],'enabled_ability_ids':enabled['enabled_ability_ids'],'family_count':21,'areas':38,'global_quests':30,'gear':25,'normal_retained_instances':21,'southern_s3_rom_bytes_parent_verified':5858700,'live_inspected_rom_bytes':5858716,'iwram_end_hex':'0x03006D28','iwram_code_boundary_hex':'0x03007000','remaining_iwram_code_bytes':728},
'cumulative_after_acceptance':{'forms':65,'families':30,'areas':46,'global_quests':38,'gear':31,'minimum_retained_individuals_for_all_branches':34},
'authoritative_allocation':{'path':'docs/SOUTHERN_CHAPTER_DESIGN.md','section':'10. Bounded route to exactly128 obtainable forms','magma_families':['F011','F012','F013','F014','F015','F016','F036','F037','F038'],'milestones':[{'name':'Southern accepted scope','ids':sorted(enabled['enabled_form_ids'])},{'name':'Magma','ids':list(range(31,49))+list(range(95,101))},{'name':'Underwater','ids':list(range(49,61))+list(range(101,109))+list(range(113,117))},{'name':'Return A','ids':[3,6,9,12,15,17,18,21,24,27,30,109,110,111,112]},{'name':'Return B','ids':list(range(61,73))+list(range(117,121))},{'name':'Legends','ids':list(range(121,129))}]},
'forms':forms,'families':families,'trial_bindings':bindings,'evolutions':edges,'rooms':roomlist,'links':links,'quests':quests,'optional_discovery_commission':comm,'equipment':gear,'field_sources':field,'branch_sources':branch,
'entry':{'from_room':30,'requires':['Q24_CLAIMED'],'method':'Explicit lift-ticket conversation at the reopened Sunlace landing. No ticket item, payment or optional quest required.','exit':'Always-returning lift to Southern room30, using its existing allowed spawn plus verified warp.'},
'contexts':[{'name':'MAGMA_READY','mask':256,'derived_from':['Q30_CLAIMED','Q31_CLAIMED']},{'name':'CALDERA_OPEN','mask':512,'derived_from':['Q32_CLAIMED']}],
'namespace':{'new_capabilities':[],'commands':list(range(43,67)),'rooms':list(range(38,46)),'quests':list(range(30,38)),'event_range':[220,259],'aid_range':[40,63],'field_visit_byte':3,'anchor_byte':3,'anchor_mask':3,'field_source_byte':9,'field_source_mask':127,'branch_receipt_byte':16,'branch_receipt_mask':15,'discovery_byte':19,'discovery_mask':7,'unassigned_aid_indices':[62,63],'quest_credit_ids':list(range(240,248)),'enemy_credit_ids':list(range(220,232)),'reserved_credit_ids':list(range(232,240))+list(range(248,260))},
'limits':{'wire_version':5,'instance_bytes':24,'instance_slots':160,'party_slots':4,'save_used_bytes':5056,'save_bank_bytes':6144,'new_iwram_bytes':0,'rom_limit_bytes':33554432,'proposed_rom_increment_limit_bytes':2097152,'new_mutable_ewram_limit_bytes':8192,'proposed_runtime_state_limit_bytes':1024,'max_simultaneous_power_objects':3,'max_visible_enemies':5,'new_permanent_obj_bytes':0,'max_learnset':8,'max_branch_copies_required':4},
'gates':[{'key':'historical_policy_isolation','status':'required_before_activation','proof':'Exact revision1–4 command/trial/quest/equipment/source/room policy snapshots; old valid banks remain valid and newly broadened states remain invalid as old revisions.'},{'key':'multi_trial_subset_policy','status':'required_before_activation','proof':'Frozen legacy scalar API; current family unions are separate; edges require own qualified subset; wrong-family and prerequisites fail byte-unchanged.'},{'key':'third_tier_validation','status':'required_before_activation','proof':'Exact tier3=285, inherited commands/capabilities and chain trials on same individual; no legacy story-tier enablement.'},{'key':'branch_choice_and_second_copy','status':'required_before_activation','proof':'Both target choices, ambiguity/defer semantics, deterministic real second and later base encounters, retained-copy receipts and full-capacity retry.'},{'key':'native_content_acceptance','status':'required_before_activation','proof':'All24 normal-controller acquired/evolved/reloaded; visual, controls, combat, route safety, interruption, performance and independent exact-ROM review.'}],
'policy':{'all_old_capabilities_unchanged':True,'all_old_form_ids_unchanged':True,'disabled_legendary_ids':list(range(121,129)),'disabled_ability_ids':[12],'no_legacy_third_tiers_enabled':True,'partial_release_not_proposed':True,'minimums_awarded_only_after_actual_same_instance_trial':True,'source_claim_ownership_atomic':True,'runtime_implementation_claimed':False,'native_verification_claimed':False},
'primary_references':[{'url':'https://whc.unesco.org/en/list/1117/','title':'UNESCO: Landscape of the Pico Island Vineyard Culture','used_for':'Dry-stone enclosure relationships and the legibility of cultivated pockets in volcanic terrain; no copied buildings, patterns, costumes or cultural claims.'},{'url':'https://www.usgs.gov/news/volcano-watch-lava-tubes','title':'USGS Hawaiian Volcano Observatory: Volcano Watch—Lava tubes (1996-08-30)','used_for':'Distinct dark tube walls, former flow marks and openings as environment reference. Fictional safe mechanisms are not volcanic safety advice.'}],
}
# Source hashes are audit metadata, not an assertion the active build is the approved final ROM.
paths=['docs/ROADMAP.md','docs/SOUTHERN_CHAPTER_DESIGN.md','docs/SOUTHERN_CORE_CONTRACT.md','docs/SOUTHERN_CORE_REVIEW.md','assets/creatures/catalog.json','assets/creatures/identity-lock.json','assets/creatures/enabled.json','assets/equipment/catalog.json','src/creatures.h','src/equipment.h','src/save5.h','linker.ld']
plan['source_hashes']={p:sha(SOURCE/p) for p in paths}
# Forward gameplay admission is a separate integration gate, never a save whitelist.
from terminal_admission import build_policy
terminal_policy=build_policy(lock)
plan['design_revision']=2
plan['terminal_admission']={
 'scope':'forward_gameplay_mutations_only',
 'capacity':160,'full_planned_terminal_opportunities':72,'extra_copy_budget':88,
 'coverage':'maximum matching of distinct retained individuals to reachable final terminal targets within each locked family',
 'safe_predicate':'occupied - viable_coverage <= 88',
 'equivalent_free_space_predicate':'160 - occupied >= 72 - viable_coverage',
 'uses_obtained_or_seen_history':False,'new_persistent_fields':0,
 'guards':['every gameplay creature grant, including repeatable grant0 wrappers','every gameplay evolution transaction that can reduce reachable terminal coverage'],
 'safe_state_candidate_rule':'admit only if occupied_after <= 160 and occupied_after - viable_coverage_after <= 88',
 'preexisting_overbudget_candidate_rule':'preserve/load/resave under unchanged declared-revision validation; allow only physical-capacity-respecting nonworsening excess and nondecreasing coverage; do not claim completion recovery',
 'bank_validation_uses_budget':False,'legacy_normalization_or_deletion':False,
 'completion_guarantee_domain':'all allowed future choice orders starting at an admission-safe state; future source/trial reachability must independently remain authored',
 'legacy_overbudget_completion_guaranteed':False,
 'source_refusal_is_byte_unchanged':True,'duplicate_source_retry_precedes_admission':True,
 'form_terminal_masks':[{ 'form_id':form,'family_id':row.family,'reachable_terminal_mask':row.terminal_mask,'terminal_form_ids':list(row.terminals)} for form,row in sorted(terminal_policy.items())]
}
plan['gates'].append({'key':'terminal_opportunity_admission','status':'required_before_activation','proof':'Preserve N−V<=88 at every new gameplay grant/evolution; all allowed choice orders from safe states retain enough slots for72 terminal opportunities. Preserve historical validation and explicitly disclose unrecoverable pre-existing excess.'})
plan['gates'].append({'key':'explicit_branch_polarity_policy','status':'required_before_activation','proof':'Proposed39/48 polarity changes require reviewed per-form current policy; current catalog family-wide polarity guard must not be bypassed. Released polarities and identity lock stay unchanged.'})
for source in plan['branch_sources']:
 source['admission_guard']='terminal_opportunity_admission'
 source['repeatable']=True
 source['repeat_limit']='terminal-opportunity admission, not an arbitrary per-family capture count'
for edge in plan['evolutions']:
 edge['activation_gates'].append('terminal_opportunity_admission')

(ROOT/'magma_allocation.json').write_text(json.dumps(plan,indent=2,ensure_ascii=False)+'\n')
(ROOT/'identity-lock.snapshot.json').write_text(json.dumps(lock,indent=2)+'\n')
# The human creature reference comes from the same rows, preventing stale IDs.
lines=['# Magma creature and command cards','\nDeveloper-only proposal; no runtime rows are enabled. All timing values are 60Hz PLAY updates, not measured balance results. Commands preserve current equipment cooldown semantics and hit ledgers.\n']
for f in forms:
 lines += [f"## {f['id']} · {f['name']} ({f['family_id']}, tier {f['tier']})",f"- Identity: {f['phase'].title()} / {f['polarity'].title()}, locked ordinary rarity; signature {f['signature_ability']}",f"- Silhouette: {f['silhouette']}",f"- Locomotion: {f['locomotion']}",f"- Field: {', '.join(f['field_caps'])}; tagged targets only",f"- Combat role: {f['combat_role']}",f"- {f['command']['name']}: {f['command']['behavior']}",f"- Timing: startup/active/recovery/cooldown { '/'.join(str(v) for v in f['command']['timing_updates'].values()) }; live objects≤{f['command']['max_live_objects']}; total target budget≤{f['command']['max_total_damage_q4_per_target']} Q4",f"- Stat weights: {f['stats']} = {f['stat_total']}; verify actual consumers before balancing",f"- Acquisition: {f['acquisition']['detail']}",f"- Learned commands: {', '.join(str(x['ability_id'])+'@'+str(x['min_level']) for x in f['learnset'])}"]
 if f['evolution']:
  e=f['evolution'];t=next(t for t in bindings if t['family_id']==f['family_id'] and t['local_trial_key']==e['local_trial_key'])
  lines += [f"- Evolution: {e['from']}→{e['to']}, level{e['min_level']}/bond{e['min_bond']}, {e['context']}, family-local key{e['local_trial_key']} (required mask{e['required_mask']}), sanctuary and explicit target confirmation",f"- Trial ‘{t['name']}’: {t['environmental_proof']}"]
 lines+=['']
(ROOT/'MAGMA_CREATURE_CARDS.md').write_text('\n'.join(lines)+'\n')
print('Wrote design-only allocation and24 creature cards; no game files changed.')
