#!/usr/bin/env python3
"""Compile all ending-roll credits into isolated, native GBJ UiRun text."""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
from gbj_font import render_text
import json
ROOT=Path(__file__).resolve().parents[1]
credits=json.loads((ROOT/'assets/ending_credits.json').read_text())
labels={name.upper():{'text':credits[name],'height':15} for name in ('title','roll_hint','card_hint','done_hint','release_hint','thanks')}
labels.update({f'LINE_{i}':{'text':line,'height':15} for i,line in enumerate(credits['lines'])})
items=[];metrics={}
for name,spec in labels.items():
 string=spec['text'];h=spec['height']
 im=render_text(string,h);w=im.width
 assert w<=214,(name,string,w)
 variants=[]
 for align in (0,1):
  runs=[]
  for y in range(h):
   masks=[sum(1<<bit for bit in (0,1) if 0<=px+bit-align<w and im.getpixel((px+bit-align,y)))for px in range(0,w+align,2)]
   x=0
   while x<len(masks):
    mask=masks[x]
    if not mask:x+=1;continue
    end=x+1
    while end<len(masks) and masks[end]==mask and end-x<255:end+=1
    runs.append((y*120+x,end-x,mask));x=end
  decoded=Image.new('1',(w+align,h))
  for offset,count,mask in runs:
   for half in range(count):
    y,x=divmod(offset+half,120)
    for bit in (0,1):
     if mask&(1<<bit):decoded.putpixel((x*2+bit,y),1)
  assert decoded.crop((align,0,w+align,h)).tobytes()==im.tobytes()
  variants.append(runs)
 items.append((name,w,h,variants));metrics[name]={**spec,'width':w,'ink_bounds':im.getbbox()}
header='#ifndef EMBER_ENDING_CREDITS_TEXT_H\n#define EMBER_ENDING_CREDITS_TEXT_H\n#include "ui.h"\nenum {\n'+''.join(f' EC_{n},\n'for n,*_ in items)+' EC_COUNT };\nextern const UiText ending_credits_texts[EC_COUNT];\n#endif\n'
(ROOT/'src/ending_credits_text.h').write_text(header)
lines=[]
for name,w,h,v in items:
 for align,runs in enumerate(v):lines.append(f'static const UiRun ec_{name}_{align}[] = {{'+(','.join('{%d,%d,%d}'%r for r in runs)if runs else'{0,0,0}')+'};\n')
lines.append('const UiText ending_credits_texts[EC_COUNT] = {\n')
for n,w,h,v in items:lines.append('{%d,%d,0,{ec_%s_0,ec_%s_1},{%d,%d}},\n'%(w,h,n,n,len(v[0]),len(v[1])))
lines.append('};\n')
folder=ROOT/'src/ending_credits_text_data';folder.mkdir(exist_ok=True)
for p in folder.glob('part_*.inc'):p.unlink()
parts=[];part=''
for line in lines:
 if len((part+line).encode())>32000:parts.append(part);part=''
 part+=line
if part:parts.append(part)
for i,part in enumerate(parts):(folder/f'part_{i:03}.inc').write_text(part)
(ROOT/'src/ending_credits_text.c').write_text('/* Generated by assets/generate_ending_credits.py. */\n#include "ending_credits_text.h"\n'+''.join(f'#include "ending_credits_text_data/part_{i:03}.inc"\n'for i in range(len(parts))))
(ROOT/'assets/ending_credits_text_metrics.json').write_text(json.dumps(metrics,ensure_ascii=False,indent=2)+'\n')
print(f'{len(items)} ending credit texts; {len(parts)} bounded chunks')
