#!/usr/bin/env python3
"""Generate isolated companion-guide raster text without changing shared UI IDs."""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
from gbj_font import render_text
import json
from companion_guide_source import load_commands
ROOT=Path(__file__).resolve().parents[1]
FONT=ImageFont.truetype('/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc',12,index=0)
labels={
 'PHASE':'五行：','POLARITY':'陰陽：',
 'COMBAT_WAIT':'戦闘の再使用', 'FRAMES':'コマ',
 'FIELD':'野外での力', 'FIELD_CONTEXT':'仕掛けは姿と技で変わる',
 'FIELD_WAIT':'仕掛けでは待ち時間が変わる',
 'WAIT_UNIT':'待ちは動ける時のコマ数',
 'BROWSE_COMBAT':'←→ 技   ↑↓ 野外の説明', 'BROWSE_FIELD':'←→ 技   ↑↓ 戦闘の説明',
 'PARTY_INSPECT':'A 詳しく・編成を確認',
 'GROWTH_KEYS':'十字 選ぶ   A 詳しく・決定',
 'EQUIP':'A 技を決定   B 戻る   START 閉じる',
 'EQUIPPED':'選択中の技   B 戻る   START 閉じる',
 'EVOLVE':'進化すると元には戻れない', 'EVOLVE_KEYS':'←→ 姿   A 進化   B 戻る',
 'EVOLVE_SINGLE_KEYS':'A 進化   B 戻る   START 閉じる',
}
for slot in range(4):
 labels[f'ASSIGN_{slot}']=f'A 枠{slot+1}へ入替  B 戻る START 閉じる'
 labels[f'ASSIGNED_{slot}']=f'枠{slot+1}に編成中  B 戻る START 閉じる'
commands=load_commands(ROOT)
assert sorted(c['id'] for c in commands)==list(range(1,129))
for c in commands:
 assert 1<=len(c['combat'])<=2 and c['field'] and c['source'] and c['recovery']
 for n,line in enumerate(c['combat']):labels[f'C{c["id"]}_{n}']=line
 if len(c['combat'])==1:labels[f'C{c["id"]}_1']=''
 labels[f'F{c["id"]}']=c['field']
# Append-only Party browsing copy: existing command and label IDs stay stable.
labels.update({'PARTY_SLASH':'/', 'PARTY_INSTANCE':'No.', 'PARTY_LEVEL':'Lv.',
               'PARTY_SLOT':'枠', 'PARTY_RESERVE':'控え',
               'PARTY_FOOTER':'A 詳細   B 戻る   START 閉じる',
               'PARTY_EMPTY_FOOTER':'A 空枠へ   B 戻る   START 閉じる'})
for digit in range(10):labels[f'PARTY_DIGIT_{digit}']=str(digit)
items=[]
for name,string in labels.items():
 h=15;im=render_text(string,h);w=im.width
 assert w<=214,(name,string,w)
 variants=[]
 for align in (0,1):
  runs=[]
  for y in range(h):
   masks=[]
   for px in range(0,w+align,2):
    mask=sum(1<<bit for bit in (0,1) if 0<=px+bit-align<w and im.getpixel((px+bit-align,y)))
    masks.append(mask)
   x=0
   while x<len(masks):
    mask=masks[x]
    if not mask:x+=1;continue
    end=x+1
    while end<len(masks) and masks[end]==mask and end-x<255:end+=1
    runs.append((y*120+x,end-x,mask));x=end
  decoded=Image.new('1',(w+align,h))
  for offset,count,mask in runs:
   for half in range(count):
    y,x=divmod(offset+half,120)
    for bit in (0,1):
     if mask&(1<<bit):decoded.putpixel((x*2+bit,y),1)
  assert decoded.crop((align,0,w+align,h)).tobytes()==im.tobytes()
  variants.append(runs)
 items.append((name,w,h,variants))
header='''#ifndef EMBER_COMPANION_GUIDE_TEXT_H
#define EMBER_COMPANION_GUIDE_TEXT_H
#include "ui.h"
enum {\n'''+''.join(f' CG_{n},\n' for n,*_ in items)+''' CG_COUNT };
typedef struct { unsigned short combat[2],field; } CompanionGuideCopy;
extern const UiText companion_guide_texts[CG_COUNT];
extern const CompanionGuideCopy companion_guide_commands[129];
#endif
'''
(ROOT/'src/companion_guide_text.h').write_text(header)
lines=[]
for name,w,h,v in items:
 for align,runs in enumerate(v):lines.append(f'static const UiRun cg_{name}_{align}[] = {{'+(','.join('{%d,%d,%d}'%r for r in runs) if runs else '{0,0,0}')+'};\n')
lines.append('const UiText companion_guide_texts[CG_COUNT] = {\n')
for n,w,h,v in items:lines.append('{%d,%d,0,{cg_%s_0,cg_%s_1},{%d,%d}},\n'%(w,h,n,n,len(v[0]),len(v[1])))
lines.append('};\nconst CompanionGuideCopy companion_guide_commands[129] = {\n{{0,0},0},\n')
for c in sorted(commands,key=lambda c:c['id']):
 i=c['id'];lines.append(f'{{{{CG_C{i}_0,CG_C{i}_1}},CG_F{i}}},\n')
lines.append('};\n')
folder=ROOT/'src/companion_guide_text_data';folder.mkdir(exist_ok=True)
for p in folder.glob('part_*.inc'):p.unlink()
parts=[];part=''
for line in lines:
 if len((part+line).encode())>32000:parts.append(part);part=''
 part+=line
if part:parts.append(part)
for i,part in enumerate(parts):(folder/f'part_{i:03}.inc').write_text(part)
(ROOT/'src/companion_guide_text.c').write_text('/* Generated by assets/generate_companion_guide.py. */\n#include "companion_guide_text.h"\n'+''.join(f'#include "companion_guide_text_data/part_{i:03}.inc"\n' for i in range(len(parts))))
(ROOT/'assets/companion_guide_text_metrics.json').write_text(json.dumps({n:{'width':w,'height':h,'text':labels[n]} for n,w,h,v in items},ensure_ascii=False,indent=2)+'\n')
print(f'{len(items)} texts,128 commands,{len(parts)} <=32KB source chunks')
