#!/usr/bin/env python3
"""Original eight-beat village opening; exact 240x160 native text and props."""
from pathlib import Path
import json,re
from PIL import Image, ImageDraw, ImageFont
from gbj_font import render_text
ROOT=Path(__file__).resolve().parents[1]
source=json.loads((ROOT/'assets/opening_scene.json').read_text())
font=ImageFont.truetype('/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc',12,index=0)
labels={'TITLE':source['title'],'CONTROLS':source['controls']}
assert len(source['pages'])==8
for p,page in enumerate(source['pages']):
 assert len(page['lines'])==2
 labels[f'SPEAKER{p}']=page['speaker']
 for i,line in enumerate(page['lines']):labels[f'LINE{p}_{i}']=line
items=[]
for name,label in labels.items():
 height=15;im=render_text(label,height);width=im.width
 assert width<=214,(name,label,width)
 variants=[]
 for align in (0,1):
  runs=[]
  for y in range(height):
   masks=[sum(1<<b for b in (0,1) if 0<=x+b-align<width and im.getpixel((x+b-align,y))) for x in range(0,width+align,2)]
   x=0
   while x<len(masks):
    if not masks[x]:x+=1;continue
    end=x+1
    while end<len(masks) and masks[end]==masks[x] and end-x<255:end+=1
    runs.append((y*120+x,end-x,masks[x]));x=end
  decoded=Image.new('1',(width+align,height))
  for offset,count,mask in runs:
   for half in range(count):
    y,x=divmod(offset+half,120)
    for b in (0,1):
     if mask&(1<<b):decoded.putpixel((x*2+b,y),1)
  assert decoded.crop((align,0,width+align,height)).tobytes()==im.tobytes()
  variants.append(runs)
 items.append((name,width,height,variants))
header=['#ifndef EMBER_OPENING_SCENE_DATA_H\n#define EMBER_OPENING_SCENE_DATA_H\n#include "ui.h"\nenum {\n']
header.extend(f' OS_{name},\n' for name,*_ in items)
header+=[' OS_TEXT_COUNT };\nextern const UiText opening_scene_texts[OS_TEXT_COUNT];\nextern const unsigned char opening_lantern[3][384];\nextern const unsigned char opening_chore_props[32*16];\n#endif\n']
(ROOT/'src/opening_scene_data.h').write_text(''.join(header))
lines=[]
for name,width,height,variants in items:
 for align,runs in enumerate(variants):lines.append(f'static const UiRun os_{name}_{align}[]={{'+','.join('{%d,%d,%d}'%r for r in runs)+'};\n')
lines.append('const UiText opening_scene_texts[OS_TEXT_COUNT]={\n')
for name,width,height,variants in items:lines.append('{%d,%d,0,{os_%s_0,os_%s_1},{%d,%d}},\n'%(width,height,name,name,len(variants[0]),len(variants[1])))
lines.append('};\n')
pal={k:int(v) for k,v in re.findall(r'#define PAL_(\w+) (\d+)',(ROOT/'src/assets.h').read_text())}
p=lambda n:pal[n]
bg=Image.open(ROOT/'assets/village.png');lanterns=[]
for level in range(3):
 im=bg.crop((112,44,128,68));d=ImageDraw.Draw(im)
 d.rectangle((6,1,9,21),fill=p('WOOD1'));d.rectangle((7,1,8,21),fill=p('WOOD3'))
 d.rectangle((3,2,12,3),fill=p('GOLD2'));d.rectangle((2,4,13,15),fill=p('WOOD1'))
 d.rectangle((3,5,12,14),fill=p('GOLD1') if level==2 else p('GOLD3'))
 d.rectangle((4,6,11,13),fill=p('WOOD2') if level==2 else p('FIRE1'))
 if level<2:
  d.polygon([(7,6+level),(10,10),(8,13),(5,11)],fill=p('GOLD4'))
  d.rectangle((7,9,8,11),fill=p('WHITE'))
 d.rectangle((2,15,13,16),fill=p('GOLD2'));d.rectangle((4,21,11,22),fill=p('WOOD2'))
 lanterns.append(im.tobytes())
props=Image.new('P',(32,16));d=ImageDraw.Draw(props)
# A small water pail and growing herb tray, in the existing native palette.
d.arc((1,1,10,10),180,360,fill=p('SILVER'));d.rectangle((1,6,10,13),fill=p('WOOD1'));d.rectangle((2,7,9,12),fill=p('WATER2'));d.line((2,7,9,7),fill=p('WATER4'))
d.rectangle((17,9,30,14),fill=p('WOOD1'));d.rectangle((18,10,29,13),fill=p('WOOD3'));d.line((18,9,29,9),fill=p('GOLD2'))
for x in (20,25,28):
 d.line((x,9,x,4),fill=p('PINE2'));d.rectangle((x-2,4,x,5),fill=p('PINE4'));d.rectangle((x,2,x+2,3),fill=p('MINT'))
lines.append('const unsigned char opening_lantern[3][384] __attribute__((aligned(4)))={\n'+',\n'.join('{'+','.join(map(str,raw))+'}' for raw in lanterns)+'\n};\n')
lines.append('const unsigned char opening_chore_props[32*16] __attribute__((aligned(4)))={'+','.join(map(str,props.tobytes()))+'};\n')
folder=ROOT/'src/opening_scene_data';folder.mkdir(exist_ok=True)
for old in folder.glob('part_*.inc'):old.unlink()
parts=[];part=''
for line in lines:
 if len((part+line).encode())>30000:parts.append(part);part=''
 part+=line
if part:parts.append(part)
for i,part in enumerate(parts):(folder/f'part_{i:03d}.inc').write_text(part)
(ROOT/'src/opening_scene_data.c').write_text('/* Generated by assets/generate_opening_scene.py. */\n#include "opening_scene_data.h"\n'+''.join(f'#include "opening_scene_data/part_{i:03d}.inc"\n' for i in range(len(parts))))
(ROOT/'assets/opening_scene_metrics.json').write_text(json.dumps({n:{'width':w,'height':h,'text':labels[n]} for n,w,h,v in items},ensure_ascii=False,indent=2)+'\n')
print(f'{len(items)} text rasters, {len(parts)} source chunks, maximum width {max(x[1] for x in items)}')
