#!/usr/bin/env python3
"""Integrate the original isolated kit without modifying its authored pixels."""
from pathlib import Path
import hashlib
import importlib.util
import json
import tempfile

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'assets/covenants_creatures'
SOURCE = ASSETS / 'source/generate_covenant_art.py'
spec = importlib.util.spec_from_file_location('covenants_source', SOURCE)
kit = importlib.util.module_from_spec(spec)
spec.loader.exec_module(kit)


def generate():
    fields, casts, portraits = kit.tensors()
    validation = kit.validate(fields, casts, portraits)
    assert validation['passed'], validation['errors']
    with tempfile.TemporaryDirectory(prefix='covenants-art-') as directory:
        kit.GEN = Path(directory)
        kit.ROOT = kit.GEN
        kit.emit(fields, casts, portraits)
        out = ROOT / 'src/covenants_creature_art_data'
        out.mkdir(exist_ok=True)
        for source in sorted((kit.GEN / 'data').glob('*.inc')):
            value = source.read_text().replace('covenant_art_', 'covenants_creature_art_')
            assert len(value.encode()) < 30000
            (out / source.name).write_text(value)
        for suffix in ('h', 'c'):
            value = (kit.GEN / ('covenant_art.' + suffix)).read_text()
            value = value.replace('covenant_art', 'covenants_creature_art')
            value = value.replace('COVENANT_ART_PROPOSAL', 'EMBERBOND_COVENANTS_CREATURE_ART')
            value = value.replace('COVENANT_ART_', 'COVENANTS_CREATURE_ART_')
            value = value.replace('CovenantArtEntry', 'CovenantsCreatureArtEntry')
            value = value.replace('"data/', '"covenants_creature_art_data/')
            value = value.replace('Generated asset proposal. No catalog, OAM, collision, or gameplay changes.',
                                  'Original indexed pixels, generated by assets/generate_covenants_creatures.py.')
            if suffix == 'h':
                value = value.replace('#endif',
                    '/* Gait uses authored per-frame durations; no simulation or private timer. */\n'
                    'unsigned covenants_creature_art_walk_index(unsigned form_id, unsigned active_ticks);\n'
                    '#endif')
            else:
                value += '''
unsigned covenants_creature_art_walk_index(unsigned form_id, unsigned active_ticks) {
    int i = covenants_creature_art_index(form_id);
    unsigned frame, total = 0;
    if (i < 0) return 0;
    for (frame = 0; frame < 4; frame++) total += covenants_creature_art_entries[i].walk_ticks[frame];
    active_ticks %= total;
    for (frame = 0; frame < 3; frame++) {
        unsigned duration = covenants_creature_art_entries[i].walk_ticks[frame];
        if (active_ticks < duration) break;
        active_ticks -= duration;
    }
    return frame;
}
'''
            (ROOT / 'src' / ('covenants_creature_art.' + suffix)).write_text(value)
    pixels = b''.join(im.tobytes() for tensor in (fields, casts)
                      for row in tensor for direction in row for im in direction)
    pixels += b''.join(im.tobytes() for im in portraits)
    assert len(pixels) == 65536
    files = sorted((ROOT / 'src/covenants_creature_art_data').glob('*.inc'))
    manifest = {'scope': 'original-native-assets; controller-motion-and-acquisition-unverified',
                'forms': list(range(121, 129)), 'images': 232, 'pixel_bytes': len(pixels),
                'pixel_sha256': hashlib.sha256(pixels).hexdigest(),
                'authored_source_sha256': hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
                'generated_parts': {str(p.relative_to(ROOT)): hashlib.sha256(p.read_bytes()).hexdigest()
                                    for p in files}, 'validation': validation}
    (ASSETS / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')


if __name__ == '__main__':
    generate()
