#!/usr/bin/env python3
"""Independent delivered-Magma over-budget synthetic wire acceptance check."""
import ctypes as C,hashlib,json,sys,tempfile
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];OUT=Path(__file__).resolve().parent
sys.path.insert(0,str(ROOT/'tests'))
from test_underwater_history_differential import build,ORACLE
from test_underwater_save import FIXTURE,FIXTURE_SHA,runtime_hashes
from test_save5 import Save,Roster,SIZE,A,compare_state
before=runtime_hashes();data=FIXTURE.read_bytes();assert hashlib.sha256(data).hexdigest()==FIXTURE_SHA
with tempfile.TemporaryDirectory(prefix='independent-old-overbudget-') as tmp:
 old=build(ORACLE,Path(tmp)/'old');new=build(ROOT,Path(tmp)/'new');state=Save();out=Save();rows=[]
 assert old.history_probe_image(data,C.byref(state))==1
 old.creatures_grant.argtypes=[C.POINTER(Roster)]+[C.c_uint]*5
 new.save5_preflight_begin.argtypes=[C.POINTER(Save)];new.save5_preflight_begin.restype=C.c_uint
 for count in (89,90,159,160):
  while sum(bool(c.form_id) for c in state.roster.instances)<count:
   assert old.creatures_grant(C.byref(state.roster),1,50,100,0,0)!=255
  bank=(C.c_ubyte*SIZE)();assert old.history_encode(C.byref(state),bank)==1;assert bytes(bank[12:14])==b'\x05\x00'
  assert new.history_probe_bank(bank,A,C.byref(out))==1;assert compare_state(state)==compare_state(out)
  token=new.save5_preflight_begin(C.byref(out));assert token
  while (status:=new.save5_preflight_step(token,1024))==1:pass
  assert status==2;new.save5_preflight_cancel()
  upgraded=(C.c_ubyte*SIZE)();assert new.history_encode(C.byref(out),upgraded)==1
  assert bytes(upgraded[12:14])==b'\x06\x00';assert new.history_probe_bank(upgraded,A,C.byref(out))==1
  assert compare_state(state)==compare_state(out)
  rows.append({'retained':count,'r5_bank_sha256':hashlib.sha256(bank).hexdigest(),'r6_bank_sha256':hashlib.sha256(upgraded).hexdigest(),'bytewise_typed_payload_preserved':True})
 assert before==runtime_hashes()
 report={'status':'pass','scope':'synthetic legal grandfathered saves generated by delivered Magma source; not native acquisition','fixture_sha256':FIXTURE_SHA,'source_hashes':before,'cases':rows}
 (OUT/'old-overbudget.json').write_text(json.dumps(report,indent=2)+'\n');print('old-overbudget acceptance, bounded preflight, r6 roundtrip:',[x['retained'] for x in rows])
