#!/usr/bin/env python3
"""Bake all24 finite optical paths using the retained pixel-step reference.

The table is data, not a gameplay cache. Regeneration reads the current authored
room solids. The original ray/first-blocker/loop rules remain in an independent
reference translation unit, also used by the exhaustive regression oracle.
"""
import argparse,json,os,subprocess,tempfile
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
DRIVER=r'''
#include <stdio.h>
#include "south_game.h"
unsigned reference_south_puzzle_beam(const SouthPuzzle*,unsigned,SouthBeam[4]);
int main(void){unsigned area,bits,i;
 for(area=34;area<=36;area++)for(bits=0;bits<8;bits++){
  SouthPuzzle p={{bits&1,(bits>>1)&1},(bits>>2)&1};SouthBeam b[4]={{0}};
  unsigned n=reference_south_puzzle_beam(&p,area,b);printf("%u",n);
  for(i=0;i<4;i++)printf(" %d %d %d %d %u",b[i].x1,b[i].y1,b[i].x2,b[i].y2,b[i].end_kind);
  puts("");
 }return 0;
}
'''
def generated():
 with tempfile.TemporaryDirectory(prefix='southern-beam-table-')as td:
  td=Path(td);(td/'driver.c').write_text(DRIVER)
  subprocess.run([os.environ.get('HOST_CC','cc'),'-std=c99','-O2','-Wall','-Wextra','-Werror','-Isrc',str(td/'driver.c'),'assets/southern_beam_reference.c','src/south_art.c','-o',str(td/'emit')],cwd=ROOT,check=True)
  rows=[list(map(int,line.split()))for line in subprocess.check_output([str(td/'emit')],text=True).splitlines()]
 assert len(rows)==24 and all(len(r)==21 and 1<=r[0]<=4 for r in rows)
 text='/* Generated by tools/generate_southern_beams.py; all24 exact optical states. */\n'
 text+='static const unsigned char south_beam_counts[24]={'+','.join(str(r[0])for r in rows)+'};\n'
 text+='static const SouthBeam south_beam_paths[24][4]={\n'
 for r in rows:text+=' {'+','.join('{'+','.join(map(str,r[1+i*5:6+i*5]))+'}'for i in range(4))+'},\n'
 return text+'};\n'
def main():
 p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');a=p.parse_args();s=generated();out=ROOT/'src/southern_beams.inc'
 if a.check:assert out.read_text()==s,'Regenerate the optical table after authored geometry changes'
 else:out.write_text(s)
 print(json.dumps({'table':str(out),'states':24,'bytes':len(s),'verified':a.check}))
if __name__=='__main__':main()
