#!/usr/bin/env python3
"""Bake the original ordered wordmark draws against their exact title backdrop.

The small patch is only used immediately after BACK_TITLE. It changes neither
the font nor compositing order, and uses no writable game memory.
"""
import argparse
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def build():
    source = (ROOT / 'src/title_route_drawing.inc').read_text()
    alphabet = re.search(r'alphabet\[26\]\[7\]=\{(.*?)\};', source, re.S).group(1)
    glyphs = [list(map(int, row.split(','))) for row in re.findall(r'\{([^}]+)\}', alphabet)]
    data = None
    collecting = False
    pieces = []
    for path in sorted((ROOT / 'src/asset_data').glob('*.inc')):
        content = path.read_text()
        if not collecting:
            match = re.search(r'background_title\[38400\]\s*=\s*\{', content)
            if not match:
                continue
            collecting = True
            content = content[match.end():]
        pieces.append(content.split('};', 1)[0])
        if '};' in content:
            data = bytearray(map(int, re.findall(r'\d+', ''.join(pieces))))
            break
    assert data is not None and len(data) == 38400
    palette = dict((name, int(value)) for name, value in re.findall(r'#define (PAL_\w+) (\d+)', (ROOT / 'src/assets.h').read_text()))
    def rect(x, y, color):
        for dy in range(3):
            data[(y + dy) * 240 + x:(y + dy) * 240 + x + 3] = bytes([color]) * 3
    for index, letter in enumerate('EMBERBOND'):
        for y, bits in enumerate(glyphs[ord(letter) - ord('A')]):
            for x in range(5):
                if bits & (16 >> x):
                    rect(43 + index * 18 + x * 3, 37 + y * 3, palette['PAL_INK'])
                    rect(42 + index * 18 + x * 3, 35 + y * 3, palette['PAL_GOLD4'] if y < 3 else palette['PAL_GOLD3'])
    rows = [data[y * 240 + 40:y * 240 + 204] for y in range(35, 58)]
    return ('/* Generated by tools/generate_feedback_title.py; exact original wordmark. */\n'
            'static const u8 feedback_title_wordmark[23][164] __attribute__((aligned(4))) = {\n' +
            ''.join(' {' + ','.join(map(str, row)) + '},\n' for row in rows) + '};\n')


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    output = ROOT / 'src/feedback_title_data.inc'
    expected = build()
    if args.check:
        assert output.read_text() == expected, 'Regenerate the exact title patch'
        print('Exact title patch is current: 3772 ROM bytes, no game RAM')
    else:
        output.write_text(expected)
