#!/usr/bin/env python3
"""Append explicit font credits after original artwork generation.

The historical artwork generator remains byte-for-byte pinned. Text fonts are
credited separately, without claiming its character/scenery art is third-party.
"""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
(ROOT/'assets/CREDITS.txt').write_text('''All character, environment, and prop artwork is original code-native pixel art authored for Emberbond.
Generated by assets/generate_assets.py using Pillow.

GBJ and GBJ-Slim bitmap fonts by GeeBee: https://geebeegb.itch.io/gbj
Official original PNG/JSON files are bundled under assets/fonts/gbj.
Usage permissions and provenance: assets/fonts/gbj/README.md.
Kanji fallback: Noto Sans CJK Bold (SIL OFL 1.1). Lowercase/symbol fallback: DejaVu Sans.
See assets/fonts/NOTO-LICENSE.txt and DEJAVU-LICENSE.txt.
''')
