#!/usr/bin/env python3
"""Compile the shared paired road manifest into bounded world-space rows."""
from pathlib import Path
import json

ROOT=Path(__file__).resolve().parents[1]
EDGES={'N':0,'E':1,'S':2,'W':3}
GATES={'none':0,'campaign_grove':1,'campaign_sky':2,'region':3,'north':4,'south':5,
       'magma':6,'underwater':7,'underwater_guardian_return':7,'return':8,'horizons':9,'covenants':10}

def compile_rows(data):
    rows=[]
    for road in data['roads']:
        a,b=road['ends']
        assert len(road['ends'])==2 and (EDGES[a['edge']]+2)%4==EDGES[b['edge']],road['key']
        for source,target in ((a,b),(b,a)):
            arrival_only=road.get('one_way',False)and source is b
            width,height=source['size'];lo,hi=source['aperture'];center=source['center']
            assert 0<=lo<center<hi<=(width if source['edge']in'NS' else height),road['key']
            assert hi-lo==target['aperture'][1]-target['aperture'][0],road['key']
            assert (lo-center,hi-center)==(target['aperture'][0]-target['center'],target['aperture'][1]-target['center']),road['key']
            ax,ay=target['arrival'];tw,th=target['size']
            assert 5<=ax<tw-5 and 5<=ay<th-5,road['key']
            rows.append((source['room'],target['room'],target['saved_spawn'],EDGES[source['edge']],
                         0 if arrival_only else GATES[target['gate']],int(target.get('entry_safe',False)),width,height,
                         lo,hi,center,target['center'],ax,ay,source.get('barrier_inset',16),int(arrival_only)))
    rows.sort(key=lambda row:(row[0],row[3],row[1]))
    assert len(rows)<256 and len({(r[0],r[1])for r in rows})==len(rows)
    for i,r in enumerate(rows):
        for q in rows[i+1:]:
            if r[0]==q[0]and r[3]==q[3]:assert r[9]<=q[8]or q[9]<=r[8],('overlapping seams',r,q)
    return rows

def main():
    data=json.loads((ROOT/'assets/connected_roads.json').read_text());rows=compile_rows(data)
    out=['/* Generated by tools/generate_connected_roads.py; edit the shared manifest. */',
         'const ConnectedRoad connected_roads[]={']
    out+=[' {'+','.join(map(str,row))+'},'for row in rows]
    out+=['};','const unsigned connected_road_count=sizeof connected_roads/sizeof connected_roads[0];',
          'static const unsigned char connected_road_ranges[78][2]={']
    for room in range(78):
        matches=[i for i,r in enumerate(rows)if r[0]==room]
        assert len(matches)<32,('room mask capacity',room)
        if matches:out.append(f' [{room}]={{{matches[0]},{matches[-1]+1}}},')
    out+=['};','']
    out+=['const ConnectedDoor connected_doors[]={']
    for door in data.get('doorways',[]):
        room,target=door['room'],door['target'];x,y,w,h=door['footprint']
        ax,ay=door['target_arrival'];bx,by=door['arrival']
        out.append(' {'+','.join(map(str,(room,target,0,0,8,0,x,y,w,h,ax,ay)))+'},')
        out.append(' {'+','.join(map(str,(target,room,door['saved_spawn'],2,3 if room==16 else 0,0,108,144,24,16,bx,by)))+'},')
    out+=['};','const unsigned connected_door_count=sizeof connected_doors/sizeof connected_doors[0];','']
    (ROOT/'src/connected_roads_data.inc').write_text('\n'.join(out))
    entries=json.loads((ROOT/'assets/feedback_travel_entries.json').read_text())['entries']
    lines=['/* Generated by tools/generate_connected_roads.py from the doorway/transport manifest. */']
    for entry in entries:
        lines.append(' {'+','.join(map(str,(entry['room'],entry['action'],entry['target'],entry['spawn'],*entry['footprint'])))+'},')
    (ROOT/'src/travel_feedback_entries.inc').write_text('\n'.join(lines)+'\n')
    print('Generated',len(rows),'directed road seams')
if __name__=='__main__':main()
