#!/usr/bin/env python3
"""Create a deterministic source-only ZIP and integrity manifest.

Only explicit project source/document/art roots are allowed. Build products,
shared toolchains, Python caches and ordinary runtime saves are never packaged.
The small pinned legacy .sav fixtures under tests/fixtures/legacy are deliberate
regression inputs generated by prior emulator runs, not user save data.
"""
from pathlib import Path
import hashlib
import json
import zipfile

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'dist'
ROOT_FILES=('.gitignore','LICENSE','Makefile','README.md','linker.ld')
SOURCE_ROOTS=('src','assets','docs','tests','tools')
EXTENSIONS={'.c','.h','.s','.inc','.py','.sh','.md','.json','.png','.gif','.txt','.sav'}
EXCLUDED={'build','dist','downloads','sysroot','__pycache__','.git'}
# Redundant large contact sheets are reproducible with make assets. Individual
# region/camera PNGs remain included; these are not ROM inputs or test fixtures.
GENERATED_OVERVIEWS={
 'assets/region/region_preview_native.png','assets/region/region_preview_2x.png',
 'assets/region/native_camera_sheet.png','assets/region/native_camera_sheet_2x.png'}

def source_files():
    files=[ROOT/p for p in ROOT_FILES]
    for name in SOURCE_ROOTS:
        for p in (ROOT/name).rglob('*'):
            rel=p.relative_to(ROOT)
            if p.is_symlink() or not p.is_file() or EXCLUDED.intersection(rel.parts):continue
            # The bridge smoke test creates a disposable color screenshot in
            # its own directory. Ship its self-generating script, not outputs.
            if rel.parts[:2]==('tools','smoke_tests') and p.name!='test_bridge.py':continue
            if rel.as_posix() in GENERATED_OVERVIEWS:continue
            if p.name=='.gitignore':files.append(p);continue
            if p.suffix not in EXTENSIONS:continue
            if p.suffix=='.sav' and not str(rel).startswith('tests/fixtures/'):continue
            files.append(p)
    return sorted(set(files),key=lambda p:p.relative_to(ROOT).as_posix())

def main():
    OUT.mkdir(exist_ok=True)
    files=source_files()
    manifest={'schema':1,'purpose':'Source-only reproducible Southern S3 release; 41 native-obtainable forms, Save5 revision4','files':[]}
    target=OUT/'Adventure-Legends-Emberbond-source.zip'
    with zipfile.ZipFile(target,'w',zipfile.ZIP_DEFLATED,compresslevel=9) as archive:
        for p in files:
            data=p.read_bytes();name=p.relative_to(ROOT).as_posix()
            manifest['files'].append({'path':name,'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest()})
            info=zipfile.ZipInfo('Adventure-Legends-Emberbond/'+name,(2026,10,5,0,0,0));info.compress_type=zipfile.ZIP_DEFLATED
            info.external_attr=(0o755 if p.suffix=='.sh' else 0o644)<<16
            archive.writestr(info,data,compresslevel=9)
    manifest['source_zip_sha256']=hashlib.sha256(target.read_bytes()).hexdigest()
    manifest['source_zip_bytes']=target.stat().st_size
    (OUT/'source-manifest-campaign.json').write_text(json.dumps(manifest,indent=2)+'\n')
    print(json.dumps({'files':len(files),'zip':str(target),'bytes':manifest['source_zip_bytes'],'sha256':manifest['source_zip_sha256']},indent=2))

if __name__=='__main__':main()
