/* Original Emberbond campaign art. Generated by assets/generate_campaign.py. */
#ifndef EMBERBOND_CAMPAIGN_ART_H
#define EMBERBOND_CAMPAIGN_ART_H
#define CAMPAIGN_ART_FIRST_ROOM 4
#define CAMPAIGN_BACKGROUND_COUNT 10
#define CAMPAIGN_COMPANION_COUNT 2
#define CAMPAIGN_BOSS_COUNT 2
/* All images are linear row-major palette indices using existing game_palette.
 * Backgrounds: opaque 240x160. Sprite zero is transparent. No new RAM buffers.
 * Companion order: Fuuri, Kohaku. Direction order: down, up, left, right.
 * Frames: idle, first contact/wing beat, raised passing, second contact/beat.
 * Sprite anchors: center (draw 16x16 at x-8,y-8; 32x32 at x-16,y-16).
 * Engine owns all dynamic obstacle/bridge/prop states and all actor drawing.
 */
enum { CAMPAIGN_COMP_FUURI, CAMPAIGN_COMP_KOHAKU };
enum { CAMPAIGN_BOSS_KAZANE, CAMPAIGN_BOSS_CORE };
enum { CAM_PROP_VANE, CAM_PROP_WEIGHT, CAM_PROP_WELL, CAM_PROP_FIRE, CAM_PROP_NATURE, CAM_PROP_WIND, CAM_PROP_STONE, CAM_PROP_BRAZIER, CAM_PROP_LAMP, CAM_PROP_REST, CAM_PROP_SIGN, CAM_PROP_CHIME, CAM_PROP_COUNT };
extern const unsigned char campaign_background_sky_path[38400];
extern const unsigned char campaign_background_sky_vanes[38400];
extern const unsigned char campaign_background_sky_patrol[38400];
extern const unsigned char campaign_background_sky_relay[38400];
extern const unsigned char campaign_background_sky_boss[38400];
extern const unsigned char campaign_background_core_path[38400];
extern const unsigned char campaign_background_core_weights[38400];
extern const unsigned char campaign_background_core_roots[38400];
extern const unsigned char campaign_background_core_lamps[38400];
extern const unsigned char campaign_background_core_boss[38400];
extern const unsigned char * const campaign_backgrounds[CAMPAIGN_BACKGROUND_COUNT];
extern const unsigned char campaign_companion_direction_frames[2][4][4][256];
extern const unsigned char campaign_boss_data[2][1024];
/* Prop state [0]=off/unlatched, [1]=on/latched. Props are optional engine utilities. */
extern const unsigned char campaign_prop_data[CAM_PROP_COUNT][2][256];
#endif
