/* Original indexed pixels, generated by assets/generate_covenants_creatures.py. */
#ifndef EMBERBOND_COVENANTS_CREATURE_ART_H
#define EMBERBOND_COVENANTS_CREATURE_ART_H
#define COVENANTS_CREATURE_ART_COUNT 8
#define COVENANTS_CREATURE_ART_PIXEL_BYTES 65536
/* IDs 121..128; direction down/up/left/right; 16x16 row-major 8bpp,
 * transparent zero, unchanged shared actor palette 0..96. Field anchor 8,8;
 * separate renderer shadow anchor 8,13. No in-sprite shadow or palette upload.
 * Cast poses anticipate/release/settle. All pointers have immutable lifetime.
 * Unsupported IDs or indices return null. Caller owns clipping and rendering. */
struct CovenantsCreatureArtEntry {
    unsigned char form_id, anchor_x, anchor_y, shadow_x, shadow_y;
    unsigned char walk_ticks[4], cast_ticks[3];
};
extern const struct CovenantsCreatureArtEntry covenants_creature_art_entries[8];
extern const unsigned char covenants_creature_art_walk[8][4][4][256];
extern const unsigned char covenants_creature_art_cast[8][4][3][256];
extern const unsigned char covenants_creature_art_portraits[8][1024];
int covenants_creature_art_index(unsigned int form_id);
const unsigned char *covenants_creature_art_frame(unsigned int form_id, unsigned int direction, unsigned int frame);
const unsigned char *covenants_creature_art_cast_frame(unsigned int form_id, unsigned int direction, unsigned int pose);
const unsigned char *covenants_creature_art_portrait(unsigned int form_id);
/* Gait uses authored per-frame durations; no simulation or private timer. */
unsigned covenants_creature_art_walk_index(unsigned form_id, unsigned active_ticks);
#endif
