/* Generated by assets/creatures/generate_data.py. Do not edit. */
#include "creatures.h"

const FormId creature_legacy_forms[4] = {1, 4, 7, 10};
const CreatureForm creature_forms[CREATURE_ENABLED_COUNT] = {
    {1, 1, 1, 1, 1, 0, {30, 50, 25, 40, 35}, 1, 0x00001222u, 1, 0, 1, 1, 0, 0, 1, 1},
    {2, 1, 1, 1, 2, 0, {42, 61, 35, 58, 44}, 5, 0x00001222u, 2, 1, 2, 0, 0, 0, 2, 1},
    {4, 2, 0, 0, 1, 0, {45, 20, 35, 50, 30}, 2, 0x00100c00u, 4, 3, 1, 1, 1, 0, 4, 1},
    {5, 2, 0, 0, 2, 0, {62, 25, 51, 67, 35}, 6, 0x00100c00u, 5, 4, 2, 0, 0, 0, 5, 1},
    {7, 3, 0, 1, 1, 0, {25, 25, 25, 45, 60}, 3, 0x000a0088u, 7, 6, 1, 1, 2, 0, 7, 1},
    {8, 3, 0, 1, 2, 0, {34, 34, 32, 64, 76}, 7, 0x000a0088u, 8, 7, 2, 0, 0, 0, 8, 1},
    {10, 4, 2, 0, 1, 0, {50, 35, 55, 20, 20}, 4, 0x00044051u, 10, 9, 1, 1, 3, 0, 10, 1},
    {11, 4, 2, 0, 2, 0, {67, 44, 76, 26, 27}, 8, 0x00044051u, 11, 10, 2, 0, 0, 0, 11, 1},
};

const CreatureLearn creature_learnsets[12] = {
    {1, 1},
    {1, 1},
    {12, 5},
    {1, 2},
    {1, 2},
    {12, 6},
    {1, 3},
    {1, 3},
    {16, 7},
    {1, 4},
    {1, 4},
    {20, 8},
};

const CreatureEvolution creature_evolutions[4] = {
    {1, 2, 12, 40, 1, 1},
    {4, 5, 12, 40, 2, 1},
    {7, 8, 16, 55, 4, 2},
    {10, 11, 20, 60, 8, 4},
};

const CreatureAbility creature_abilities[8] = {
    {1, 1, 75, 0x00001222u},
    {2, 0, 75, 0x00100c00u},
    {3, 0, 75, 0x000a0088u},
    {4, 2, 75, 0x00044051u},
    {5, 1, 105, 0x00001222u},
    {6, 0, 120, 0x00100c00u},
    {7, 0, 105, 0x000a0088u},
    {8, 2, 120, 0x00044051u},
};

const char *creatures_name(unsigned form_id) {
    switch (form_id) {
    case 1: return "Homura";
    case 2: return "Homura Hearthkeeper";
    case 4: return "Midori";
    case 5: return "Midori Canopykeeper";
    case 7: return "Fuuri";
    case 8: return "Fuuri Windweaver";
    case 10: return "Kohaku";
    case 11: return "Kohaku Archwarden";
    default: return "Unavailable form";
    }
}

const char *creatures_ability_name(unsigned ability_id) {
    switch (ability_id) {
    case 1: return "Ember Dart";
    case 2: return "Root Circle";
    case 3: return "Gust Fan";
    case 4: return "Stone Guard";
    case 5: return "Hearthline";
    case 6: return "Canopy Knot";
    case 7: return "Slipstream Loom";
    case 8: return "Vaultstep";
    default: return "No command";
    }
}
