/* Generated by assets/generate_ending_credits.py. */
#include "ending_credits_text.h"
#include "ending_credits_text_data/part_000.inc"
#include "ending_credits_text_data/part_001.inc"
#include "ending_credits_text_data/part_002.inc"
#include "ending_credits_text_data/part_003.inc"
