/* Generated by assets/equipment/generate_data.py; do not hand edit. */
#include "equipment.h"

const EquipmentItemId equipment_authored_ids[EQUIPMENT_AUTHORED_COUNT] = {
    1, 2, 9, 10, 17, 18, 33, 34, 49, 50, 65, 81, 82
};

const EquipmentDefinition equipment_definitions[EQUIPMENT_DEFINITION_CAPACITY] = {
    [1] = {1, 0, 1, 1, 255, {0, 0}, {0, 0, 0, 0, 0, 0, 0, 0}},
    [2] = {2, 0, 1, 0, 255, {0, 0}, {4, 1, 0, 0, 0, 0, 0, 0}},
    [9] = {9, 0, 2, 0, 255, {0, 0}, {0, 0, 0, 0, 0, 0, 0, 0}},
    [10] = {10, 0, 2, 0, 255, {0, 0}, {4, 0, 0, 0, 0, 0, 0, 1}},
    [17] = {17, 0, 3, 0, 255, {0, 0}, {0, 0, 0, 0, 0, 0, 0, 0}},
    [18] = {18, 0, 3, 0, 255, {0, 0}, {4, 0, 0, 0, 0, 0, 0, 0}},
    [33] = {33, 1, 0, 0, 255, {0, 0}, {0, 2, 8, -4, 0, 0, 0, 0}},
    [34] = {34, 1, 0, 0, 255, {0, 0}, {0, 4, 16, -8, 0, 0, 0, 0}},
    [49] = {49, 2, 0, 0, 255, {0, 0}, {0, 0, 0, 8, 0, 0, 0, 0}},
    [50] = {50, 2, 0, 0, 255, {0, 0}, {0, 0, 0, 0, 3, 0, 0, 0}},
    [65] = {65, 3, 0, 0, 255, {0, 0}, {0, 0, 8, 0, 0, 0, 0, 0}},
    [81] = {81, 4, 0, 0, 255, {0, 0}, {0, 0, 0, 0, 0, 4, 0, 0}},
    [82] = {82, 4, 0, 0, 255, {0, 0}, {0, 1, 0, 0, 0, 0, 0, 1}},
};

const EquipmentWeapon equipment_weapons[4] = {
    [1] = {1, 3, 44, 8, 384, 0, 0, 0, 0, 0, {{2, 1, 14, 32, 29, 18}, {2, 1, 14, 32, 29, 18}, {3, 1, 20, 48, 35, 20}}},
    [2] = {2, 1, 0, 6, 256, 0, 0, 0, 0, 0, {{6, 3, 20, 48, 43, 6}, {0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0}}},
    [3] = {3, 2, 0, 0, 0, 1024, 24, 45, 2, 0, {{4, 1, 23, 32, 112, 3}, {24, 1, 23, 48, 144, 3}, {0, 0, 0, 0, 0, 0}}},
};

const char *equipment_name(unsigned id) {
    switch (id) {
    case 1: return "Wayfarer Sword";
    case 2: return "Reedguard Sword";
    case 9: return "Practice Lance";
    case 10: return "Copperleaf Lance";
    case 17: return "Travel Bow";
    case 18: return "Tidewood Bow";
    case 33: return "Patchwork Mail";
    case 34: return "Hearthscale Mail";
    case 49: return "Trail Boots";
    case 50: return "Surestep Boots";
    case 65: return "Woven Belt";
    case 81: return "Resonance Ring";
    case 82: return "Steady Ring";
    default: return "Empty";
    }
}

const char *equipment_description(unsigned id, unsigned line) {
    if (line > 1) return "";
    switch (id) {
    case 1: return line ? "Cannot be discarded." : "A trusty close-range sword.";
    case 2: return line ? "Attack +4; defense +1." : "A sturdier close-range cut.";
    case 9: return line ? "Long reach; watch your sides." : "A narrow, committed thrust.";
    case 10: return line ? "Attack +4; stagger +1." : "Copperleaf tips hold firm.";
    case 17: return line ? "Arrows carry no field magic." : "Aim and release to fire.";
    case 18: return line ? "Attack +4 on each arrow." : "A steady bow for long roads.";
    case 33: return line ? "Defense +2; speed -4." : "A half-heart of padding.";
    case 34: return line ? "Defense +4; speed -8." : "A heart of layered armor.";
    case 49: return line ? "Walking speed +8." : "Light soles for the trail.";
    case 50: return line ? "Roll cooldown -3." : "Sure footing after a dodge.";
    case 65: return line ? "Maximum health +half-heart." : "A packmaker's sturdy belt.";
    case 81: return line ? "Power cooldown -4." : "A clear note for companions.";
    case 82: return line ? "Defense +1; stagger +1." : "A ring that steadies the hand.";
    default: return "";
    }
}
