#include "evolution_art.h"
/* Generated by assets/generate_evolutions.py. */
#include "evolution_art_data/part_000.inc"
#include "evolution_art_data/part_001.inc"

int evolution_art_index(unsigned int form_id) {
    switch (form_id) {
    case 2: return EVOLUTION_HOMURA_HEARTHKEEPER;
    case 5: return EVOLUTION_MIDORI_CANOPYKEEPER;
    case 8: return EVOLUTION_FUURI_WINDWEAVER;
    case 11: return EVOLUTION_KOHAKU_ARCHWARDEN;
    default: return -1;
    }
}
const unsigned char *evolution_art_frame(unsigned int form_id, unsigned int direction, unsigned int frame) {
    int index = evolution_art_index(form_id);
    if (index < 0 || direction >= 4 || frame >= 4) return (const unsigned char *)0;
    return evolution_companion_direction_frames[index][direction][frame];
}
const unsigned char *evolution_art_portrait(unsigned int form_id) {
    int index = evolution_art_index(form_id);
    return index < 0 ? (const unsigned char *)0 : evolution_portraits[index];
}
