#ifndef EMBER_GEAR_PREVIEW_TEXT_H
#define EMBER_GEAR_PREVIEW_TEXT_H
#include "ui.h"
enum {
 GP_TITLE,
 GP_EQUIPPED,
 GP_PREVIEW,
 GP_ATTACK,
 GP_DEFENSE,
 GP_HEART,
 GP_WALK,
 GP_RECOVERY,
 GP_DISTANCE,
 GP_STAGGER,
 GP_SWORD,
 GP_LANCE,
 GP_BOW,
 GP_RECOVERY_CAP,
 GP_STAGGER_CAP,
 GP_SAME,
 GP_NO_COMMAND,
 GP_UNITS,
 GP_FOOTER,
 GP_LEFT,
 GP_RIGHT,
 GP_UP,
 GP_DOWN,
 GP_COUNT };
extern const UiText gear_preview_texts[GP_COUNT];
#endif
