/* Generated by assets/generate_gear_preview.py. */
#include "gear_preview_text.h"
#include "gear_preview_text_data/part_000.inc"
#include "gear_preview_text_data/part_001.inc"
#include "gear_preview_text_data/part_002.inc"
