/* Generated by assets/generate_opening_scene.py. */
#include "opening_scene_data.h"
#include "opening_scene_data/part_000.inc"
#include "opening_scene_data/part_001.inc"
#include "opening_scene_data/part_002.inc"
