/* Generated by assets/generate_region.py. Original regional art. */
#ifndef EMBERBOND_REGION_ART_H
#define EMBERBOND_REGION_ART_H
#define REGION_ART_FIRST_ROOM 16
#define REGION_ART_ROOM_COUNT 6
#define REGION_ART_FOOT_RADIUS 5
/* Pixel centers use a five-pixel foot radius. Rectangles are half-open. */
typedef struct { short x, y, w, h; } RegionArtRect;
typedef struct {
    unsigned short width, height;
    const unsigned char *bitmap;
    /* Row-local left-shift atlas; NULL in stationary 240x160 interiors.
       Odd camera X: source = bitmap_odd + y*width + camera_x - 1.
       Even camera X: source = bitmap + y*width + camera_x.
       Source atlases are aligned(4); copy 240 bytes for each of 160 rows. */
    const unsigned char *bitmap_odd;
    const RegionArtRect *solids;
    unsigned short solid_count;
} RegionArtRoom;
extern const RegionArtRoom region_art_rooms[REGION_ART_ROOM_COUNT];
/* All runtime actors/stateful props remain separate. Center anchor: x-8,y-8.
   Zero is transparent. Sprite data is ROW MAJOR, matching obj_upload input. */
enum {
    REGION_SPR_NPC_SMITH = 0,
    REGION_SPR_NPC_WEAVER = 1,
    REGION_SPR_NPC_WARDEN = 2,
    REGION_SPR_NPC_REST_KEEPER = 3,
    REGION_SPR_NPC_APPRENTICE = 4,
    REGION_SPR_NPC_MERCHANT = 5,
    REGION_SPR_RACK_SWORD = 6,
    REGION_SPR_RACK_LANCE = 7,
    REGION_SPR_RACK_BOW = 8,
    REGION_SPR_TARGET_READY = 9,
    REGION_SPR_TARGET_HIT = 10,
    REGION_SPR_RESET_IDLE = 11,
    REGION_SPR_RESET_LIT = 12,
    REGION_SPR_SLUICE_CLOSED = 13,
    REGION_SPR_SLUICE_OPEN = 14,
    REGION_SPR_BELL_IDLE = 15,
    REGION_SPR_BELL_RING = 16,
    REGION_SPR_LATCH_CLOSED = 17,
    REGION_SPR_LATCH_OPEN = 18,
    REGION_SPR_CRATE = 19,
    REGION_SPR_PLATE_UP = 20,
    REGION_SPR_PLATE_DOWN = 21,
    REGION_SPR_POOL_LOW = 22,
    REGION_SPR_POOL_HIGH = 23,
    REGION_SPR_BRIDGE_WOOD = 24,
    REGION_SPR_BRIDGE_ROOT = 25,
    REGION_SPR_REST_IDLE = 26,
    REGION_SPR_REST_LIT = 27,
    REGION_SPR_SIGN_WORKSHOP = 28,
    REGION_SPR_SIGN_WEAVER = 29,
    REGION_SPR_SIGN_GARDEN = 30,
    REGION_SPR_SIGN_TIDE = 31,
    REGION_SPR_REED_SCREEN = 32,
    REGION_SPR_REED_PARTED = 33,
    REGION_SPR_SPINDLE_IDLE = 34,
    REGION_SPR_SPINDLE_LIT = 35,
    REGION_SPR_FURNACE_IDLE = 36,
    REGION_SPR_FURNACE_LIT = 37,
    REGION_SPR_STEP_IDLE = 38,
    REGION_SPR_STEP_LIT = 39,
    REGION_SPR_COUNT = 40
};
extern const unsigned char region_sprites[REGION_SPR_COUNT][256];
extern const unsigned char region_background_reedhaven[153600];
extern const unsigned char region_background_reedhaven_odd[153600];
#define REGION_REEDHAVEN_SOLID_COUNT 39
extern const RegionArtRect region_reedhaven_solids[REGION_REEDHAVEN_SOLID_COUNT];
extern const unsigned char region_background_reedbasin[153600];
extern const unsigned char region_background_reedbasin_odd[153600];
#define REGION_REEDBASIN_SOLID_COUNT 39
extern const RegionArtRect region_reedbasin_solids[REGION_REEDBASIN_SOLID_COUNT];
extern const unsigned char region_background_bellfoundry[38400];
#define REGION_BELLFOUNDRY_SOLID_COUNT 10
extern const RegionArtRect region_bellfoundry_solids[REGION_BELLFOUNDRY_SOLID_COUNT];
extern const unsigned char region_background_tide_courtyard[38400];
#define REGION_TIDE_COURTYARD_SOLID_COUNT 7
extern const RegionArtRect region_tide_courtyard_solids[REGION_TIDE_COURTYARD_SOLID_COUNT];
extern const unsigned char region_background_mira_storehouse[38400];
#define REGION_MIRA_STOREHOUSE_SOLID_COUNT 8
extern const RegionArtRect region_mira_storehouse_solids[REGION_MIRA_STOREHOUSE_SOLID_COUNT];
extern const unsigned char region_background_surestep_garden[38400];
#define REGION_SURESTEP_GARDEN_SOLID_COUNT 9
extern const RegionArtRect region_surestep_garden_solids[REGION_SURESTEP_GARDEN_SOLID_COUNT];
#endif
