#include "regional_creature_art.h"
/* Generated by assets/generate_regional_creatures.py. */
#include "regional_creature_art_data/part_000.inc"
#include "regional_creature_art_data/part_001.inc"

int regional_creature_art_index(unsigned int form_id) {
    switch (form_id) {
    case 13: return REGIONAL_CREATURE_DEWSPINDLE;
    case 14: return REGIONAL_CREATURE_TIDEWHEEL;
    case 16: return REGIONAL_CREATURE_CHIMECLASP;
    default: return -1;
    }
}
const unsigned char *regional_creature_art_frame(unsigned int form_id, unsigned int direction, unsigned int frame) {
    int i = regional_creature_art_index(form_id);
    if (i < 0 || direction >= 4 || frame >= 4) return (const unsigned char *)0;
    return regional_creature_direction_frames[i][direction][frame];
}
const unsigned char *regional_creature_art_ability_frame(unsigned int form_id, unsigned int direction, unsigned int pose) {
    int i = regional_creature_art_index(form_id);
    if (i < 0 || direction >= 4 || pose >= 2) return (const unsigned char *)0;
    return regional_creature_ability_frames[i][direction][pose];
}
const unsigned char *regional_creature_art_portrait(unsigned int form_id) {
    int i = regional_creature_art_index(form_id);
    return i < 0 ? (const unsigned char *)0 : regional_creature_portraits[i];
}
