#ifndef EMBER_TREASURE_TEXT_TEXT_H
#define EMBER_TREASURE_TEXT_TEXT_H
#include "ui.h"
enum {
 TT_TITLE,
 TT_COMPASS,
 TT_LENS,
 TT_BELL,
 TT_PEARL,
 TT_COMPASS_EFFECT,
 TT_LENS_EFFECT,
 TT_BELL_EFFECT,
 TT_PEARL_EFFECT,
 TT_PERMANENT,
 TT_RECEIPT_KEYS,
 TT_CLAIM,
 TT_CLAIM_HINT,
 TT_KNOWN,
 TT_COUNT };
extern const UiText treasure_text_texts[TT_COUNT];
#endif
