/* Generated by assets/generate_world.py. Original Sunmere Grove artwork. */
#ifndef EMBERBOND_WORLD_H
#define EMBERBOND_WORLD_H
#define WORLD_W 480
#define WORLD_H 320
#define WORLD_RIVER_Y 156
#define WORLD_RIVER_H 20
#define WORLD_BRIDGE_X 228
#define WORLD_BRIDGE_W 24
#define WORLD_TEMPLE_GATE_X 352
#define WORLD_TEMPLE_GATE_Y 28
#define WORLD_TEMPLE_GATE_W 33
#define WORLD_TEMPLE_GATE_H 8
#define WORLD_SPAWN_X 240
#define WORLD_SPAWN_Y 287
#define WORLD_VILLAGE_EXIT_X 240
#define WORLD_VILLAGE_EXIT_Y 304
#define WORLD_BRIDGE_CENTER_X 240
#define WORLD_BRIDGE_Y 166
#define WORLD_BRIDGE_CENTER_Y 166
#define WORLD_CAMP_X 120
#define WORLD_CAMP_Y 248
#define WORLD_CHEST_X 92
#define WORLD_CHEST_Y 72
#define WORLD_TEMPLE_X 368
#define WORLD_TEMPLE_Y 24
#define OVERWORLD_SOLID_COUNT 76
#define WORLD_SOLID_COUNT OVERWORLD_SOLID_COUNT
/* Half-open rectangles: x <= point.x < x+w, y <= point.y < y+h.
   These are scenery only. Add world bounds and the dynamic river/bridge in game.c.
   The campfire and chest are drawn and controlled by the engine. */
typedef struct { short x,y,w,h; } WorldRect;
extern const unsigned char overworld_bitmap[WORLD_W * WORLD_H];
/* Row-local one-pixel left shift. For odd camera X, use offset camera_x-1
   into this aligned bitmap for the same pixels with DMA16-safe addressing. */
extern const unsigned char overworld_bitmap_odd[WORLD_W * WORLD_H];
extern const WorldRect overworld_solids[OVERWORLD_SOLID_COUNT];
extern const unsigned int overworld_solid_count;
enum {
    WORLD_SPR_CAMP_IDLE, WORLD_SPR_CAMP_LIT,
    WORLD_SPR_CHEST_CLOSED, WORLD_SPR_CHEST_OPEN,
    WORLD_SPR_RANGER_IDLE, WORLD_SPR_RANGER_WINDUP, WORLD_SPR_COUNT
};
extern const unsigned char world_sprites[WORLD_SPR_COUNT][256];
#endif
